package com.spring.fee.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class JcMemberExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jc_member
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jc_member
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jc_member
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_member
     *
     * @mbggenerated
     */
    public JcMemberExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_member
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_member
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_member
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_member
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_member
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_member
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_member
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_member
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_member
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_member
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jc_member
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andParentIdIsNull() {
            addCriterion("parent_id is null");
            return (Criteria) this;
        }

        public Criteria andParentIdIsNotNull() {
            addCriterion("parent_id is not null");
            return (Criteria) this;
        }

        public Criteria andParentIdEqualTo(Integer value) {
            addCriterion("parent_id =", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotEqualTo(Integer value) {
            addCriterion("parent_id <>", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdGreaterThan(Integer value) {
            addCriterion("parent_id >", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("parent_id >=", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLessThan(Integer value) {
            addCriterion("parent_id <", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLessThanOrEqualTo(Integer value) {
            addCriterion("parent_id <=", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdIn(List<Integer> values) {
            addCriterion("parent_id in", values, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotIn(List<Integer> values) {
            addCriterion("parent_id not in", values, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdBetween(Integer value1, Integer value2) {
            addCriterion("parent_id between", value1, value2, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotBetween(Integer value1, Integer value2) {
            addCriterion("parent_id not between", value1, value2, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdsIsNull() {
            addCriterion("parent_ids is null");
            return (Criteria) this;
        }

        public Criteria andParentIdsIsNotNull() {
            addCriterion("parent_ids is not null");
            return (Criteria) this;
        }

        public Criteria andParentIdsEqualTo(String value) {
            addCriterion("parent_ids =", value, "parentIds");
            return (Criteria) this;
        }

        public Criteria andParentIdsNotEqualTo(String value) {
            addCriterion("parent_ids <>", value, "parentIds");
            return (Criteria) this;
        }

        public Criteria andParentIdsGreaterThan(String value) {
            addCriterion("parent_ids >", value, "parentIds");
            return (Criteria) this;
        }

        public Criteria andParentIdsGreaterThanOrEqualTo(String value) {
            addCriterion("parent_ids >=", value, "parentIds");
            return (Criteria) this;
        }

        public Criteria andParentIdsLessThan(String value) {
            addCriterion("parent_ids <", value, "parentIds");
            return (Criteria) this;
        }

        public Criteria andParentIdsLessThanOrEqualTo(String value) {
            addCriterion("parent_ids <=", value, "parentIds");
            return (Criteria) this;
        }

        public Criteria andParentIdsLike(String value) {
            addCriterion("parent_ids like", value, "parentIds");
            return (Criteria) this;
        }

        public Criteria andParentIdsNotLike(String value) {
            addCriterion("parent_ids not like", value, "parentIds");
            return (Criteria) this;
        }

        public Criteria andParentIdsIn(List<String> values) {
            addCriterion("parent_ids in", values, "parentIds");
            return (Criteria) this;
        }

        public Criteria andParentIdsNotIn(List<String> values) {
            addCriterion("parent_ids not in", values, "parentIds");
            return (Criteria) this;
        }

        public Criteria andParentIdsBetween(String value1, String value2) {
            addCriterion("parent_ids between", value1, value2, "parentIds");
            return (Criteria) this;
        }

        public Criteria andParentIdsNotBetween(String value1, String value2) {
            addCriterion("parent_ids not between", value1, value2, "parentIds");
            return (Criteria) this;
        }

        public Criteria andSuperiorIsNull() {
            addCriterion("superior is null");
            return (Criteria) this;
        }

        public Criteria andSuperiorIsNotNull() {
            addCriterion("superior is not null");
            return (Criteria) this;
        }

        public Criteria andSuperiorEqualTo(String value) {
            addCriterion("superior =", value, "superior");
            return (Criteria) this;
        }

        public Criteria andSuperiorNotEqualTo(String value) {
            addCriterion("superior <>", value, "superior");
            return (Criteria) this;
        }

        public Criteria andSuperiorGreaterThan(String value) {
            addCriterion("superior >", value, "superior");
            return (Criteria) this;
        }

        public Criteria andSuperiorGreaterThanOrEqualTo(String value) {
            addCriterion("superior >=", value, "superior");
            return (Criteria) this;
        }

        public Criteria andSuperiorLessThan(String value) {
            addCriterion("superior <", value, "superior");
            return (Criteria) this;
        }

        public Criteria andSuperiorLessThanOrEqualTo(String value) {
            addCriterion("superior <=", value, "superior");
            return (Criteria) this;
        }

        public Criteria andSuperiorLike(String value) {
            addCriterion("superior like", value, "superior");
            return (Criteria) this;
        }

        public Criteria andSuperiorNotLike(String value) {
            addCriterion("superior not like", value, "superior");
            return (Criteria) this;
        }

        public Criteria andSuperiorIn(List<String> values) {
            addCriterion("superior in", values, "superior");
            return (Criteria) this;
        }

        public Criteria andSuperiorNotIn(List<String> values) {
            addCriterion("superior not in", values, "superior");
            return (Criteria) this;
        }

        public Criteria andSuperiorBetween(String value1, String value2) {
            addCriterion("superior between", value1, value2, "superior");
            return (Criteria) this;
        }

        public Criteria andSuperiorNotBetween(String value1, String value2) {
            addCriterion("superior not between", value1, value2, "superior");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("username is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("username is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("username =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("username <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("username >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("username >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("username <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("username <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("username like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("username not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("username in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("username not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("username between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("username not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andLevelIdIsNull() {
            addCriterion("level_id is null");
            return (Criteria) this;
        }

        public Criteria andLevelIdIsNotNull() {
            addCriterion("level_id is not null");
            return (Criteria) this;
        }

        public Criteria andLevelIdEqualTo(Integer value) {
            addCriterion("level_id =", value, "levelId");
            return (Criteria) this;
        }

        public Criteria andLevelIdNotEqualTo(Integer value) {
            addCriterion("level_id <>", value, "levelId");
            return (Criteria) this;
        }

        public Criteria andLevelIdGreaterThan(Integer value) {
            addCriterion("level_id >", value, "levelId");
            return (Criteria) this;
        }

        public Criteria andLevelIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("level_id >=", value, "levelId");
            return (Criteria) this;
        }

        public Criteria andLevelIdLessThan(Integer value) {
            addCriterion("level_id <", value, "levelId");
            return (Criteria) this;
        }

        public Criteria andLevelIdLessThanOrEqualTo(Integer value) {
            addCriterion("level_id <=", value, "levelId");
            return (Criteria) this;
        }

        public Criteria andLevelIdIn(List<Integer> values) {
            addCriterion("level_id in", values, "levelId");
            return (Criteria) this;
        }

        public Criteria andLevelIdNotIn(List<Integer> values) {
            addCriterion("level_id not in", values, "levelId");
            return (Criteria) this;
        }

        public Criteria andLevelIdBetween(Integer value1, Integer value2) {
            addCriterion("level_id between", value1, value2, "levelId");
            return (Criteria) this;
        }

        public Criteria andLevelIdNotBetween(Integer value1, Integer value2) {
            addCriterion("level_id not between", value1, value2, "levelId");
            return (Criteria) this;
        }

        public Criteria andNicknameIsNull() {
            addCriterion("nickname is null");
            return (Criteria) this;
        }

        public Criteria andNicknameIsNotNull() {
            addCriterion("nickname is not null");
            return (Criteria) this;
        }

        public Criteria andNicknameEqualTo(String value) {
            addCriterion("nickname =", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotEqualTo(String value) {
            addCriterion("nickname <>", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameGreaterThan(String value) {
            addCriterion("nickname >", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameGreaterThanOrEqualTo(String value) {
            addCriterion("nickname >=", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameLessThan(String value) {
            addCriterion("nickname <", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameLessThanOrEqualTo(String value) {
            addCriterion("nickname <=", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameLike(String value) {
            addCriterion("nickname like", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotLike(String value) {
            addCriterion("nickname not like", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameIn(List<String> values) {
            addCriterion("nickname in", values, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotIn(List<String> values) {
            addCriterion("nickname not in", values, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameBetween(String value1, String value2) {
            addCriterion("nickname between", value1, value2, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotBetween(String value1, String value2) {
            addCriterion("nickname not between", value1, value2, "nickname");
            return (Criteria) this;
        }

        public Criteria andUseTagIsNull() {
            addCriterion("use_tag is null");
            return (Criteria) this;
        }

        public Criteria andUseTagIsNotNull() {
            addCriterion("use_tag is not null");
            return (Criteria) this;
        }

        public Criteria andUseTagEqualTo(Boolean value) {
            addCriterion("use_tag =", value, "useTag");
            return (Criteria) this;
        }

        public Criteria andUseTagNotEqualTo(Boolean value) {
            addCriterion("use_tag <>", value, "useTag");
            return (Criteria) this;
        }

        public Criteria andUseTagGreaterThan(Boolean value) {
            addCriterion("use_tag >", value, "useTag");
            return (Criteria) this;
        }

        public Criteria andUseTagGreaterThanOrEqualTo(Boolean value) {
            addCriterion("use_tag >=", value, "useTag");
            return (Criteria) this;
        }

        public Criteria andUseTagLessThan(Boolean value) {
            addCriterion("use_tag <", value, "useTag");
            return (Criteria) this;
        }

        public Criteria andUseTagLessThanOrEqualTo(Boolean value) {
            addCriterion("use_tag <=", value, "useTag");
            return (Criteria) this;
        }

        public Criteria andUseTagIn(List<Boolean> values) {
            addCriterion("use_tag in", values, "useTag");
            return (Criteria) this;
        }

        public Criteria andUseTagNotIn(List<Boolean> values) {
            addCriterion("use_tag not in", values, "useTag");
            return (Criteria) this;
        }

        public Criteria andUseTagBetween(Boolean value1, Boolean value2) {
            addCriterion("use_tag between", value1, value2, "useTag");
            return (Criteria) this;
        }

        public Criteria andUseTagNotBetween(Boolean value1, Boolean value2) {
            addCriterion("use_tag not between", value1, value2, "useTag");
            return (Criteria) this;
        }

        public Criteria andUseStampIsNull() {
            addCriterion("use_stamp is null");
            return (Criteria) this;
        }

        public Criteria andUseStampIsNotNull() {
            addCriterion("use_stamp is not null");
            return (Criteria) this;
        }

        public Criteria andUseStampEqualTo(String value) {
            addCriterion("use_stamp =", value, "useStamp");
            return (Criteria) this;
        }

        public Criteria andUseStampNotEqualTo(String value) {
            addCriterion("use_stamp <>", value, "useStamp");
            return (Criteria) this;
        }

        public Criteria andUseStampGreaterThan(String value) {
            addCriterion("use_stamp >", value, "useStamp");
            return (Criteria) this;
        }

        public Criteria andUseStampGreaterThanOrEqualTo(String value) {
            addCriterion("use_stamp >=", value, "useStamp");
            return (Criteria) this;
        }

        public Criteria andUseStampLessThan(String value) {
            addCriterion("use_stamp <", value, "useStamp");
            return (Criteria) this;
        }

        public Criteria andUseStampLessThanOrEqualTo(String value) {
            addCriterion("use_stamp <=", value, "useStamp");
            return (Criteria) this;
        }

        public Criteria andUseStampLike(String value) {
            addCriterion("use_stamp like", value, "useStamp");
            return (Criteria) this;
        }

        public Criteria andUseStampNotLike(String value) {
            addCriterion("use_stamp not like", value, "useStamp");
            return (Criteria) this;
        }

        public Criteria andUseStampIn(List<String> values) {
            addCriterion("use_stamp in", values, "useStamp");
            return (Criteria) this;
        }

        public Criteria andUseStampNotIn(List<String> values) {
            addCriterion("use_stamp not in", values, "useStamp");
            return (Criteria) this;
        }

        public Criteria andUseStampBetween(String value1, String value2) {
            addCriterion("use_stamp between", value1, value2, "useStamp");
            return (Criteria) this;
        }

        public Criteria andUseStampNotBetween(String value1, String value2) {
            addCriterion("use_stamp not between", value1, value2, "useStamp");
            return (Criteria) this;
        }

        public Criteria andUsePasswordIsNull() {
            addCriterion("use_password is null");
            return (Criteria) this;
        }

        public Criteria andUsePasswordIsNotNull() {
            addCriterion("use_password is not null");
            return (Criteria) this;
        }

        public Criteria andUsePasswordEqualTo(String value) {
            addCriterion("use_password =", value, "usePassword");
            return (Criteria) this;
        }

        public Criteria andUsePasswordNotEqualTo(String value) {
            addCriterion("use_password <>", value, "usePassword");
            return (Criteria) this;
        }

        public Criteria andUsePasswordGreaterThan(String value) {
            addCriterion("use_password >", value, "usePassword");
            return (Criteria) this;
        }

        public Criteria andUsePasswordGreaterThanOrEqualTo(String value) {
            addCriterion("use_password >=", value, "usePassword");
            return (Criteria) this;
        }

        public Criteria andUsePasswordLessThan(String value) {
            addCriterion("use_password <", value, "usePassword");
            return (Criteria) this;
        }

        public Criteria andUsePasswordLessThanOrEqualTo(String value) {
            addCriterion("use_password <=", value, "usePassword");
            return (Criteria) this;
        }

        public Criteria andUsePasswordLike(String value) {
            addCriterion("use_password like", value, "usePassword");
            return (Criteria) this;
        }

        public Criteria andUsePasswordNotLike(String value) {
            addCriterion("use_password not like", value, "usePassword");
            return (Criteria) this;
        }

        public Criteria andUsePasswordIn(List<String> values) {
            addCriterion("use_password in", values, "usePassword");
            return (Criteria) this;
        }

        public Criteria andUsePasswordNotIn(List<String> values) {
            addCriterion("use_password not in", values, "usePassword");
            return (Criteria) this;
        }

        public Criteria andUsePasswordBetween(String value1, String value2) {
            addCriterion("use_password between", value1, value2, "usePassword");
            return (Criteria) this;
        }

        public Criteria andUsePasswordNotBetween(String value1, String value2) {
            addCriterion("use_password not between", value1, value2, "usePassword");
            return (Criteria) this;
        }

        public Criteria andObfuscationCodeIsNull() {
            addCriterion("obfuscation_code is null");
            return (Criteria) this;
        }

        public Criteria andObfuscationCodeIsNotNull() {
            addCriterion("obfuscation_code is not null");
            return (Criteria) this;
        }

        public Criteria andObfuscationCodeEqualTo(String value) {
            addCriterion("obfuscation_code =", value, "obfuscationCode");
            return (Criteria) this;
        }

        public Criteria andObfuscationCodeNotEqualTo(String value) {
            addCriterion("obfuscation_code <>", value, "obfuscationCode");
            return (Criteria) this;
        }

        public Criteria andObfuscationCodeGreaterThan(String value) {
            addCriterion("obfuscation_code >", value, "obfuscationCode");
            return (Criteria) this;
        }

        public Criteria andObfuscationCodeGreaterThanOrEqualTo(String value) {
            addCriterion("obfuscation_code >=", value, "obfuscationCode");
            return (Criteria) this;
        }

        public Criteria andObfuscationCodeLessThan(String value) {
            addCriterion("obfuscation_code <", value, "obfuscationCode");
            return (Criteria) this;
        }

        public Criteria andObfuscationCodeLessThanOrEqualTo(String value) {
            addCriterion("obfuscation_code <=", value, "obfuscationCode");
            return (Criteria) this;
        }

        public Criteria andObfuscationCodeLike(String value) {
            addCriterion("obfuscation_code like", value, "obfuscationCode");
            return (Criteria) this;
        }

        public Criteria andObfuscationCodeNotLike(String value) {
            addCriterion("obfuscation_code not like", value, "obfuscationCode");
            return (Criteria) this;
        }

        public Criteria andObfuscationCodeIn(List<String> values) {
            addCriterion("obfuscation_code in", values, "obfuscationCode");
            return (Criteria) this;
        }

        public Criteria andObfuscationCodeNotIn(List<String> values) {
            addCriterion("obfuscation_code not in", values, "obfuscationCode");
            return (Criteria) this;
        }

        public Criteria andObfuscationCodeBetween(String value1, String value2) {
            addCriterion("obfuscation_code between", value1, value2, "obfuscationCode");
            return (Criteria) this;
        }

        public Criteria andObfuscationCodeNotBetween(String value1, String value2) {
            addCriterion("obfuscation_code not between", value1, value2, "obfuscationCode");
            return (Criteria) this;
        }

        public Criteria andUseEmailIsNull() {
            addCriterion("use_email is null");
            return (Criteria) this;
        }

        public Criteria andUseEmailIsNotNull() {
            addCriterion("use_email is not null");
            return (Criteria) this;
        }

        public Criteria andUseEmailEqualTo(String value) {
            addCriterion("use_email =", value, "useEmail");
            return (Criteria) this;
        }

        public Criteria andUseEmailNotEqualTo(String value) {
            addCriterion("use_email <>", value, "useEmail");
            return (Criteria) this;
        }

        public Criteria andUseEmailGreaterThan(String value) {
            addCriterion("use_email >", value, "useEmail");
            return (Criteria) this;
        }

        public Criteria andUseEmailGreaterThanOrEqualTo(String value) {
            addCriterion("use_email >=", value, "useEmail");
            return (Criteria) this;
        }

        public Criteria andUseEmailLessThan(String value) {
            addCriterion("use_email <", value, "useEmail");
            return (Criteria) this;
        }

        public Criteria andUseEmailLessThanOrEqualTo(String value) {
            addCriterion("use_email <=", value, "useEmail");
            return (Criteria) this;
        }

        public Criteria andUseEmailLike(String value) {
            addCriterion("use_email like", value, "useEmail");
            return (Criteria) this;
        }

        public Criteria andUseEmailNotLike(String value) {
            addCriterion("use_email not like", value, "useEmail");
            return (Criteria) this;
        }

        public Criteria andUseEmailIn(List<String> values) {
            addCriterion("use_email in", values, "useEmail");
            return (Criteria) this;
        }

        public Criteria andUseEmailNotIn(List<String> values) {
            addCriterion("use_email not in", values, "useEmail");
            return (Criteria) this;
        }

        public Criteria andUseEmailBetween(String value1, String value2) {
            addCriterion("use_email between", value1, value2, "useEmail");
            return (Criteria) this;
        }

        public Criteria andUseEmailNotBetween(String value1, String value2) {
            addCriterion("use_email not between", value1, value2, "useEmail");
            return (Criteria) this;
        }

        public Criteria andUsePhoneIsNull() {
            addCriterion("use_phone is null");
            return (Criteria) this;
        }

        public Criteria andUsePhoneIsNotNull() {
            addCriterion("use_phone is not null");
            return (Criteria) this;
        }

        public Criteria andUsePhoneEqualTo(String value) {
            addCriterion("use_phone =", value, "usePhone");
            return (Criteria) this;
        }

        public Criteria andUsePhoneNotEqualTo(String value) {
            addCriterion("use_phone <>", value, "usePhone");
            return (Criteria) this;
        }

        public Criteria andUsePhoneGreaterThan(String value) {
            addCriterion("use_phone >", value, "usePhone");
            return (Criteria) this;
        }

        public Criteria andUsePhoneGreaterThanOrEqualTo(String value) {
            addCriterion("use_phone >=", value, "usePhone");
            return (Criteria) this;
        }

        public Criteria andUsePhoneLessThan(String value) {
            addCriterion("use_phone <", value, "usePhone");
            return (Criteria) this;
        }

        public Criteria andUsePhoneLessThanOrEqualTo(String value) {
            addCriterion("use_phone <=", value, "usePhone");
            return (Criteria) this;
        }

        public Criteria andUsePhoneLike(String value) {
            addCriterion("use_phone like", value, "usePhone");
            return (Criteria) this;
        }

        public Criteria andUsePhoneNotLike(String value) {
            addCriterion("use_phone not like", value, "usePhone");
            return (Criteria) this;
        }

        public Criteria andUsePhoneIn(List<String> values) {
            addCriterion("use_phone in", values, "usePhone");
            return (Criteria) this;
        }

        public Criteria andUsePhoneNotIn(List<String> values) {
            addCriterion("use_phone not in", values, "usePhone");
            return (Criteria) this;
        }

        public Criteria andUsePhoneBetween(String value1, String value2) {
            addCriterion("use_phone between", value1, value2, "usePhone");
            return (Criteria) this;
        }

        public Criteria andUsePhoneNotBetween(String value1, String value2) {
            addCriterion("use_phone not between", value1, value2, "usePhone");
            return (Criteria) this;
        }

        public Criteria andLevelLastUpdateIsNull() {
            addCriterion("level_last_update is null");
            return (Criteria) this;
        }

        public Criteria andLevelLastUpdateIsNotNull() {
            addCriterion("level_last_update is not null");
            return (Criteria) this;
        }

        public Criteria andLevelLastUpdateEqualTo(Date value) {
            addCriterion("level_last_update =", value, "levelLastUpdate");
            return (Criteria) this;
        }

        public Criteria andLevelLastUpdateNotEqualTo(Date value) {
            addCriterion("level_last_update <>", value, "levelLastUpdate");
            return (Criteria) this;
        }

        public Criteria andLevelLastUpdateGreaterThan(Date value) {
            addCriterion("level_last_update >", value, "levelLastUpdate");
            return (Criteria) this;
        }

        public Criteria andLevelLastUpdateGreaterThanOrEqualTo(Date value) {
            addCriterion("level_last_update >=", value, "levelLastUpdate");
            return (Criteria) this;
        }

        public Criteria andLevelLastUpdateLessThan(Date value) {
            addCriterion("level_last_update <", value, "levelLastUpdate");
            return (Criteria) this;
        }

        public Criteria andLevelLastUpdateLessThanOrEqualTo(Date value) {
            addCriterion("level_last_update <=", value, "levelLastUpdate");
            return (Criteria) this;
        }

        public Criteria andLevelLastUpdateIn(List<Date> values) {
            addCriterion("level_last_update in", values, "levelLastUpdate");
            return (Criteria) this;
        }

        public Criteria andLevelLastUpdateNotIn(List<Date> values) {
            addCriterion("level_last_update not in", values, "levelLastUpdate");
            return (Criteria) this;
        }

        public Criteria andLevelLastUpdateBetween(Date value1, Date value2) {
            addCriterion("level_last_update between", value1, value2, "levelLastUpdate");
            return (Criteria) this;
        }

        public Criteria andLevelLastUpdateNotBetween(Date value1, Date value2) {
            addCriterion("level_last_update not between", value1, value2, "levelLastUpdate");
            return (Criteria) this;
        }

        public Criteria andLastLoginIpIsNull() {
            addCriterion("last_login_ip is null");
            return (Criteria) this;
        }

        public Criteria andLastLoginIpIsNotNull() {
            addCriterion("last_login_ip is not null");
            return (Criteria) this;
        }

        public Criteria andLastLoginIpEqualTo(String value) {
            addCriterion("last_login_ip =", value, "lastLoginIp");
            return (Criteria) this;
        }

        public Criteria andLastLoginIpNotEqualTo(String value) {
            addCriterion("last_login_ip <>", value, "lastLoginIp");
            return (Criteria) this;
        }

        public Criteria andLastLoginIpGreaterThan(String value) {
            addCriterion("last_login_ip >", value, "lastLoginIp");
            return (Criteria) this;
        }

        public Criteria andLastLoginIpGreaterThanOrEqualTo(String value) {
            addCriterion("last_login_ip >=", value, "lastLoginIp");
            return (Criteria) this;
        }

        public Criteria andLastLoginIpLessThan(String value) {
            addCriterion("last_login_ip <", value, "lastLoginIp");
            return (Criteria) this;
        }

        public Criteria andLastLoginIpLessThanOrEqualTo(String value) {
            addCriterion("last_login_ip <=", value, "lastLoginIp");
            return (Criteria) this;
        }

        public Criteria andLastLoginIpLike(String value) {
            addCriterion("last_login_ip like", value, "lastLoginIp");
            return (Criteria) this;
        }

        public Criteria andLastLoginIpNotLike(String value) {
            addCriterion("last_login_ip not like", value, "lastLoginIp");
            return (Criteria) this;
        }

        public Criteria andLastLoginIpIn(List<String> values) {
            addCriterion("last_login_ip in", values, "lastLoginIp");
            return (Criteria) this;
        }

        public Criteria andLastLoginIpNotIn(List<String> values) {
            addCriterion("last_login_ip not in", values, "lastLoginIp");
            return (Criteria) this;
        }

        public Criteria andLastLoginIpBetween(String value1, String value2) {
            addCriterion("last_login_ip between", value1, value2, "lastLoginIp");
            return (Criteria) this;
        }

        public Criteria andLastLoginIpNotBetween(String value1, String value2) {
            addCriterion("last_login_ip not between", value1, value2, "lastLoginIp");
            return (Criteria) this;
        }

        public Criteria andLoginErrorCountIsNull() {
            addCriterion("login_error_count is null");
            return (Criteria) this;
        }

        public Criteria andLoginErrorCountIsNotNull() {
            addCriterion("login_error_count is not null");
            return (Criteria) this;
        }

        public Criteria andLoginErrorCountEqualTo(Integer value) {
            addCriterion("login_error_count =", value, "loginErrorCount");
            return (Criteria) this;
        }

        public Criteria andLoginErrorCountNotEqualTo(Integer value) {
            addCriterion("login_error_count <>", value, "loginErrorCount");
            return (Criteria) this;
        }

        public Criteria andLoginErrorCountGreaterThan(Integer value) {
            addCriterion("login_error_count >", value, "loginErrorCount");
            return (Criteria) this;
        }

        public Criteria andLoginErrorCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("login_error_count >=", value, "loginErrorCount");
            return (Criteria) this;
        }

        public Criteria andLoginErrorCountLessThan(Integer value) {
            addCriterion("login_error_count <", value, "loginErrorCount");
            return (Criteria) this;
        }

        public Criteria andLoginErrorCountLessThanOrEqualTo(Integer value) {
            addCriterion("login_error_count <=", value, "loginErrorCount");
            return (Criteria) this;
        }

        public Criteria andLoginErrorCountIn(List<Integer> values) {
            addCriterion("login_error_count in", values, "loginErrorCount");
            return (Criteria) this;
        }

        public Criteria andLoginErrorCountNotIn(List<Integer> values) {
            addCriterion("login_error_count not in", values, "loginErrorCount");
            return (Criteria) this;
        }

        public Criteria andLoginErrorCountBetween(Integer value1, Integer value2) {
            addCriterion("login_error_count between", value1, value2, "loginErrorCount");
            return (Criteria) this;
        }

        public Criteria andLoginErrorCountNotBetween(Integer value1, Integer value2) {
            addCriterion("login_error_count not between", value1, value2, "loginErrorCount");
            return (Criteria) this;
        }

        public Criteria andLoginCountIsNull() {
            addCriterion("login_count is null");
            return (Criteria) this;
        }

        public Criteria andLoginCountIsNotNull() {
            addCriterion("login_count is not null");
            return (Criteria) this;
        }

        public Criteria andLoginCountEqualTo(Integer value) {
            addCriterion("login_count =", value, "loginCount");
            return (Criteria) this;
        }

        public Criteria andLoginCountNotEqualTo(Integer value) {
            addCriterion("login_count <>", value, "loginCount");
            return (Criteria) this;
        }

        public Criteria andLoginCountGreaterThan(Integer value) {
            addCriterion("login_count >", value, "loginCount");
            return (Criteria) this;
        }

        public Criteria andLoginCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("login_count >=", value, "loginCount");
            return (Criteria) this;
        }

        public Criteria andLoginCountLessThan(Integer value) {
            addCriterion("login_count <", value, "loginCount");
            return (Criteria) this;
        }

        public Criteria andLoginCountLessThanOrEqualTo(Integer value) {
            addCriterion("login_count <=", value, "loginCount");
            return (Criteria) this;
        }

        public Criteria andLoginCountIn(List<Integer> values) {
            addCriterion("login_count in", values, "loginCount");
            return (Criteria) this;
        }

        public Criteria andLoginCountNotIn(List<Integer> values) {
            addCriterion("login_count not in", values, "loginCount");
            return (Criteria) this;
        }

        public Criteria andLoginCountBetween(Integer value1, Integer value2) {
            addCriterion("login_count between", value1, value2, "loginCount");
            return (Criteria) this;
        }

        public Criteria andLoginCountNotBetween(Integer value1, Integer value2) {
            addCriterion("login_count not between", value1, value2, "loginCount");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeIsNull() {
            addCriterion("last_login_time is null");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeIsNotNull() {
            addCriterion("last_login_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeEqualTo(Date value) {
            addCriterion("last_login_time =", value, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeNotEqualTo(Date value) {
            addCriterion("last_login_time <>", value, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeGreaterThan(Date value) {
            addCriterion("last_login_time >", value, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_login_time >=", value, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeLessThan(Date value) {
            addCriterion("last_login_time <", value, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeLessThanOrEqualTo(Date value) {
            addCriterion("last_login_time <=", value, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeIn(List<Date> values) {
            addCriterion("last_login_time in", values, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeNotIn(List<Date> values) {
            addCriterion("last_login_time not in", values, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeBetween(Date value1, Date value2) {
            addCriterion("last_login_time between", value1, value2, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeNotBetween(Date value1, Date value2) {
            addCriterion("last_login_time not between", value1, value2, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andIsEnabledIsNull() {
            addCriterion("is_enabled is null");
            return (Criteria) this;
        }

        public Criteria andIsEnabledIsNotNull() {
            addCriterion("is_enabled is not null");
            return (Criteria) this;
        }

        public Criteria andIsEnabledEqualTo(Boolean value) {
            addCriterion("is_enabled =", value, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledNotEqualTo(Boolean value) {
            addCriterion("is_enabled <>", value, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledGreaterThan(Boolean value) {
            addCriterion("is_enabled >", value, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_enabled >=", value, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledLessThan(Boolean value) {
            addCriterion("is_enabled <", value, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledLessThanOrEqualTo(Boolean value) {
            addCriterion("is_enabled <=", value, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledIn(List<Boolean> values) {
            addCriterion("is_enabled in", values, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledNotIn(List<Boolean> values) {
            addCriterion("is_enabled not in", values, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledBetween(Boolean value1, Boolean value2) {
            addCriterion("is_enabled between", value1, value2, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_enabled not between", value1, value2, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andLastPasswordChangeIsNull() {
            addCriterion("last_password_change is null");
            return (Criteria) this;
        }

        public Criteria andLastPasswordChangeIsNotNull() {
            addCriterion("last_password_change is not null");
            return (Criteria) this;
        }

        public Criteria andLastPasswordChangeEqualTo(Date value) {
            addCriterion("last_password_change =", value, "lastPasswordChange");
            return (Criteria) this;
        }

        public Criteria andLastPasswordChangeNotEqualTo(Date value) {
            addCriterion("last_password_change <>", value, "lastPasswordChange");
            return (Criteria) this;
        }

        public Criteria andLastPasswordChangeGreaterThan(Date value) {
            addCriterion("last_password_change >", value, "lastPasswordChange");
            return (Criteria) this;
        }

        public Criteria andLastPasswordChangeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_password_change >=", value, "lastPasswordChange");
            return (Criteria) this;
        }

        public Criteria andLastPasswordChangeLessThan(Date value) {
            addCriterion("last_password_change <", value, "lastPasswordChange");
            return (Criteria) this;
        }

        public Criteria andLastPasswordChangeLessThanOrEqualTo(Date value) {
            addCriterion("last_password_change <=", value, "lastPasswordChange");
            return (Criteria) this;
        }

        public Criteria andLastPasswordChangeIn(List<Date> values) {
            addCriterion("last_password_change in", values, "lastPasswordChange");
            return (Criteria) this;
        }

        public Criteria andLastPasswordChangeNotIn(List<Date> values) {
            addCriterion("last_password_change not in", values, "lastPasswordChange");
            return (Criteria) this;
        }

        public Criteria andLastPasswordChangeBetween(Date value1, Date value2) {
            addCriterion("last_password_change between", value1, value2, "lastPasswordChange");
            return (Criteria) this;
        }

        public Criteria andLastPasswordChangeNotBetween(Date value1, Date value2) {
            addCriterion("last_password_change not between", value1, value2, "lastPasswordChange");
            return (Criteria) this;
        }

        public Criteria andLastOrderTimeIsNull() {
            addCriterion("last_order_time is null");
            return (Criteria) this;
        }

        public Criteria andLastOrderTimeIsNotNull() {
            addCriterion("last_order_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastOrderTimeEqualTo(Date value) {
            addCriterion("last_order_time =", value, "lastOrderTime");
            return (Criteria) this;
        }

        public Criteria andLastOrderTimeNotEqualTo(Date value) {
            addCriterion("last_order_time <>", value, "lastOrderTime");
            return (Criteria) this;
        }

        public Criteria andLastOrderTimeGreaterThan(Date value) {
            addCriterion("last_order_time >", value, "lastOrderTime");
            return (Criteria) this;
        }

        public Criteria andLastOrderTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_order_time >=", value, "lastOrderTime");
            return (Criteria) this;
        }

        public Criteria andLastOrderTimeLessThan(Date value) {
            addCriterion("last_order_time <", value, "lastOrderTime");
            return (Criteria) this;
        }

        public Criteria andLastOrderTimeLessThanOrEqualTo(Date value) {
            addCriterion("last_order_time <=", value, "lastOrderTime");
            return (Criteria) this;
        }

        public Criteria andLastOrderTimeIn(List<Date> values) {
            addCriterion("last_order_time in", values, "lastOrderTime");
            return (Criteria) this;
        }

        public Criteria andLastOrderTimeNotIn(List<Date> values) {
            addCriterion("last_order_time not in", values, "lastOrderTime");
            return (Criteria) this;
        }

        public Criteria andLastOrderTimeBetween(Date value1, Date value2) {
            addCriterion("last_order_time between", value1, value2, "lastOrderTime");
            return (Criteria) this;
        }

        public Criteria andLastOrderTimeNotBetween(Date value1, Date value2) {
            addCriterion("last_order_time not between", value1, value2, "lastOrderTime");
            return (Criteria) this;
        }

        public Criteria andUniquePushIdIsNull() {
            addCriterion("unique_push_id is null");
            return (Criteria) this;
        }

        public Criteria andUniquePushIdIsNotNull() {
            addCriterion("unique_push_id is not null");
            return (Criteria) this;
        }

        public Criteria andUniquePushIdEqualTo(String value) {
            addCriterion("unique_push_id =", value, "uniquePushId");
            return (Criteria) this;
        }

        public Criteria andUniquePushIdNotEqualTo(String value) {
            addCriterion("unique_push_id <>", value, "uniquePushId");
            return (Criteria) this;
        }

        public Criteria andUniquePushIdGreaterThan(String value) {
            addCriterion("unique_push_id >", value, "uniquePushId");
            return (Criteria) this;
        }

        public Criteria andUniquePushIdGreaterThanOrEqualTo(String value) {
            addCriterion("unique_push_id >=", value, "uniquePushId");
            return (Criteria) this;
        }

        public Criteria andUniquePushIdLessThan(String value) {
            addCriterion("unique_push_id <", value, "uniquePushId");
            return (Criteria) this;
        }

        public Criteria andUniquePushIdLessThanOrEqualTo(String value) {
            addCriterion("unique_push_id <=", value, "uniquePushId");
            return (Criteria) this;
        }

        public Criteria andUniquePushIdLike(String value) {
            addCriterion("unique_push_id like", value, "uniquePushId");
            return (Criteria) this;
        }

        public Criteria andUniquePushIdNotLike(String value) {
            addCriterion("unique_push_id not like", value, "uniquePushId");
            return (Criteria) this;
        }

        public Criteria andUniquePushIdIn(List<String> values) {
            addCriterion("unique_push_id in", values, "uniquePushId");
            return (Criteria) this;
        }

        public Criteria andUniquePushIdNotIn(List<String> values) {
            addCriterion("unique_push_id not in", values, "uniquePushId");
            return (Criteria) this;
        }

        public Criteria andUniquePushIdBetween(String value1, String value2) {
            addCriterion("unique_push_id between", value1, value2, "uniquePushId");
            return (Criteria) this;
        }

        public Criteria andUniquePushIdNotBetween(String value1, String value2) {
            addCriterion("unique_push_id not between", value1, value2, "uniquePushId");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("create_user =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("create_user <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("create_user >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("create_user >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("create_user <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("create_user <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("create_user like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("create_user not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("create_user in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("create_user not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("create_user between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("create_user not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("update_user is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("update_user is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(String value) {
            addCriterion("update_user =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(String value) {
            addCriterion("update_user <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(String value) {
            addCriterion("update_user >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
            addCriterion("update_user >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(String value) {
            addCriterion("update_user <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(String value) {
            addCriterion("update_user <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLike(String value) {
            addCriterion("update_user like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotLike(String value) {
            addCriterion("update_user not like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<String> values) {
            addCriterion("update_user in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<String> values) {
            addCriterion("update_user not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(String value1, String value2) {
            addCriterion("update_user between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(String value1, String value2) {
            addCriterion("update_user not between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagIsNull() {
            addCriterion("deleted_flag is null");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagIsNotNull() {
            addCriterion("deleted_flag is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagEqualTo(Boolean value) {
            addCriterion("deleted_flag =", value, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagNotEqualTo(Boolean value) {
            addCriterion("deleted_flag <>", value, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagGreaterThan(Boolean value) {
            addCriterion("deleted_flag >", value, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagGreaterThanOrEqualTo(Boolean value) {
            addCriterion("deleted_flag >=", value, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagLessThan(Boolean value) {
            addCriterion("deleted_flag <", value, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagLessThanOrEqualTo(Boolean value) {
            addCriterion("deleted_flag <=", value, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagIn(List<Boolean> values) {
            addCriterion("deleted_flag in", values, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagNotIn(List<Boolean> values) {
            addCriterion("deleted_flag not in", values, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagBetween(Boolean value1, Boolean value2) {
            addCriterion("deleted_flag between", value1, value2, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagNotBetween(Boolean value1, Boolean value2) {
            addCriterion("deleted_flag not between", value1, value2, "deletedFlag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jc_member
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jc_member
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}