package com.spring.fee.model;

import java.io.Serializable;
import java.util.Date;

public class TableMember implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_member.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_member.member_id
     *
     * @mbggenerated
     */
    private String memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_member.reference_id
     *
     * @mbggenerated
     */
    private String referenceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_member.arrange_id
     *
     * @mbggenerated
     */
    private String arrangeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_member.left_or_right
     *
     * @mbggenerated
     */
    private Integer leftOrRight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_member.register_from
     *
     * @mbggenerated
     */
    private Integer registerFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_member.phone
     *
     * @mbggenerated
     */
    private Integer phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_member.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_member.level
     *
     * @mbggenerated
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_member.rank
     *
     * @mbggenerated
     */
    private Integer rank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_member.flag
     *
     * @mbggenerated
     */
    private Integer flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_member.account_money
     *
     * @mbggenerated
     */
    private Float accountMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_member.account_point
     *
     * @mbggenerated
     */
    private Float accountPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_member.account_dj_point
     *
     * @mbggenerated
     */
    private Float accountDjPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_member.account_jsy_point
     *
     * @mbggenerated
     */
    private Float accountJsyPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_member.aut_flag
     *
     * @mbggenerated
     */
    private Integer autFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_member.really_name
     *
     * @mbggenerated
     */
    private String reallyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_member.cart_id
     *
     * @mbggenerated
     */
    private String cartId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_member.bank_card_id
     *
     * @mbggenerated
     */
    private String bankCardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_member.bank_name
     *
     * @mbggenerated
     */
    private String bankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_member.bank_open_are
     *
     * @mbggenerated
     */
    private String bankOpenAre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_member.cart_img1
     *
     * @mbggenerated
     */
    private String cartImg1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_member.cart_img2
     *
     * @mbggenerated
     */
    private String cartImg2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_member.cart_img3
     *
     * @mbggenerated
     */
    private String cartImg3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_member.bank_img1
     *
     * @mbggenerated
     */
    private String bankImg1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_member.bank_img2
     *
     * @mbggenerated
     */
    private String bankImg2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_member.register_time
     *
     * @mbggenerated
     */
    private Date registerTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_member.last_login_time
     *
     * @mbggenerated
     */
    private Date lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_member.perfomance_time
     *
     * @mbggenerated
     */
    private Date perfomanceTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table table_member
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_member.id
     *
     * @return the value of table_member.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_member.id
     *
     * @param id the value for table_member.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_member.member_id
     *
     * @return the value of table_member.member_id
     *
     * @mbggenerated
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_member.member_id
     *
     * @param memberId the value for table_member.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId == null ? null : memberId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_member.reference_id
     *
     * @return the value of table_member.reference_id
     *
     * @mbggenerated
     */
    public String getReferenceId() {
        return referenceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_member.reference_id
     *
     * @param referenceId the value for table_member.reference_id
     *
     * @mbggenerated
     */
    public void setReferenceId(String referenceId) {
        this.referenceId = referenceId == null ? null : referenceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_member.arrange_id
     *
     * @return the value of table_member.arrange_id
     *
     * @mbggenerated
     */
    public String getArrangeId() {
        return arrangeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_member.arrange_id
     *
     * @param arrangeId the value for table_member.arrange_id
     *
     * @mbggenerated
     */
    public void setArrangeId(String arrangeId) {
        this.arrangeId = arrangeId == null ? null : arrangeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_member.left_or_right
     *
     * @return the value of table_member.left_or_right
     *
     * @mbggenerated
     */
    public Integer getLeftOrRight() {
        return leftOrRight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_member.left_or_right
     *
     * @param leftOrRight the value for table_member.left_or_right
     *
     * @mbggenerated
     */
    public void setLeftOrRight(Integer leftOrRight) {
        this.leftOrRight = leftOrRight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_member.register_from
     *
     * @return the value of table_member.register_from
     *
     * @mbggenerated
     */
    public Integer getRegisterFrom() {
        return registerFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_member.register_from
     *
     * @param registerFrom the value for table_member.register_from
     *
     * @mbggenerated
     */
    public void setRegisterFrom(Integer registerFrom) {
        this.registerFrom = registerFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_member.phone
     *
     * @return the value of table_member.phone
     *
     * @mbggenerated
     */
    public Integer getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_member.phone
     *
     * @param phone the value for table_member.phone
     *
     * @mbggenerated
     */
    public void setPhone(Integer phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_member.password
     *
     * @return the value of table_member.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_member.password
     *
     * @param password the value for table_member.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_member.level
     *
     * @return the value of table_member.level
     *
     * @mbggenerated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_member.level
     *
     * @param level the value for table_member.level
     *
     * @mbggenerated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_member.rank
     *
     * @return the value of table_member.rank
     *
     * @mbggenerated
     */
    public Integer getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_member.rank
     *
     * @param rank the value for table_member.rank
     *
     * @mbggenerated
     */
    public void setRank(Integer rank) {
        this.rank = rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_member.flag
     *
     * @return the value of table_member.flag
     *
     * @mbggenerated
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_member.flag
     *
     * @param flag the value for table_member.flag
     *
     * @mbggenerated
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_member.account_money
     *
     * @return the value of table_member.account_money
     *
     * @mbggenerated
     */
    public Float getAccountMoney() {
        return accountMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_member.account_money
     *
     * @param accountMoney the value for table_member.account_money
     *
     * @mbggenerated
     */
    public void setAccountMoney(Float accountMoney) {
        this.accountMoney = accountMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_member.account_point
     *
     * @return the value of table_member.account_point
     *
     * @mbggenerated
     */
    public Float getAccountPoint() {
        return accountPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_member.account_point
     *
     * @param accountPoint the value for table_member.account_point
     *
     * @mbggenerated
     */
    public void setAccountPoint(Float accountPoint) {
        this.accountPoint = accountPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_member.account_dj_point
     *
     * @return the value of table_member.account_dj_point
     *
     * @mbggenerated
     */
    public Float getAccountDjPoint() {
        return accountDjPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_member.account_dj_point
     *
     * @param accountDjPoint the value for table_member.account_dj_point
     *
     * @mbggenerated
     */
    public void setAccountDjPoint(Float accountDjPoint) {
        this.accountDjPoint = accountDjPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_member.account_jsy_point
     *
     * @return the value of table_member.account_jsy_point
     *
     * @mbggenerated
     */
    public Float getAccountJsyPoint() {
        return accountJsyPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_member.account_jsy_point
     *
     * @param accountJsyPoint the value for table_member.account_jsy_point
     *
     * @mbggenerated
     */
    public void setAccountJsyPoint(Float accountJsyPoint) {
        this.accountJsyPoint = accountJsyPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_member.aut_flag
     *
     * @return the value of table_member.aut_flag
     *
     * @mbggenerated
     */
    public Integer getAutFlag() {
        return autFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_member.aut_flag
     *
     * @param autFlag the value for table_member.aut_flag
     *
     * @mbggenerated
     */
    public void setAutFlag(Integer autFlag) {
        this.autFlag = autFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_member.really_name
     *
     * @return the value of table_member.really_name
     *
     * @mbggenerated
     */
    public String getReallyName() {
        return reallyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_member.really_name
     *
     * @param reallyName the value for table_member.really_name
     *
     * @mbggenerated
     */
    public void setReallyName(String reallyName) {
        this.reallyName = reallyName == null ? null : reallyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_member.cart_id
     *
     * @return the value of table_member.cart_id
     *
     * @mbggenerated
     */
    public String getCartId() {
        return cartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_member.cart_id
     *
     * @param cartId the value for table_member.cart_id
     *
     * @mbggenerated
     */
    public void setCartId(String cartId) {
        this.cartId = cartId == null ? null : cartId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_member.bank_card_id
     *
     * @return the value of table_member.bank_card_id
     *
     * @mbggenerated
     */
    public String getBankCardId() {
        return bankCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_member.bank_card_id
     *
     * @param bankCardId the value for table_member.bank_card_id
     *
     * @mbggenerated
     */
    public void setBankCardId(String bankCardId) {
        this.bankCardId = bankCardId == null ? null : bankCardId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_member.bank_name
     *
     * @return the value of table_member.bank_name
     *
     * @mbggenerated
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_member.bank_name
     *
     * @param bankName the value for table_member.bank_name
     *
     * @mbggenerated
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_member.bank_open_are
     *
     * @return the value of table_member.bank_open_are
     *
     * @mbggenerated
     */
    public String getBankOpenAre() {
        return bankOpenAre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_member.bank_open_are
     *
     * @param bankOpenAre the value for table_member.bank_open_are
     *
     * @mbggenerated
     */
    public void setBankOpenAre(String bankOpenAre) {
        this.bankOpenAre = bankOpenAre == null ? null : bankOpenAre.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_member.cart_img1
     *
     * @return the value of table_member.cart_img1
     *
     * @mbggenerated
     */
    public String getCartImg1() {
        return cartImg1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_member.cart_img1
     *
     * @param cartImg1 the value for table_member.cart_img1
     *
     * @mbggenerated
     */
    public void setCartImg1(String cartImg1) {
        this.cartImg1 = cartImg1 == null ? null : cartImg1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_member.cart_img2
     *
     * @return the value of table_member.cart_img2
     *
     * @mbggenerated
     */
    public String getCartImg2() {
        return cartImg2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_member.cart_img2
     *
     * @param cartImg2 the value for table_member.cart_img2
     *
     * @mbggenerated
     */
    public void setCartImg2(String cartImg2) {
        this.cartImg2 = cartImg2 == null ? null : cartImg2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_member.cart_img3
     *
     * @return the value of table_member.cart_img3
     *
     * @mbggenerated
     */
    public String getCartImg3() {
        return cartImg3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_member.cart_img3
     *
     * @param cartImg3 the value for table_member.cart_img3
     *
     * @mbggenerated
     */
    public void setCartImg3(String cartImg3) {
        this.cartImg3 = cartImg3 == null ? null : cartImg3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_member.bank_img1
     *
     * @return the value of table_member.bank_img1
     *
     * @mbggenerated
     */
    public String getBankImg1() {
        return bankImg1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_member.bank_img1
     *
     * @param bankImg1 the value for table_member.bank_img1
     *
     * @mbggenerated
     */
    public void setBankImg1(String bankImg1) {
        this.bankImg1 = bankImg1 == null ? null : bankImg1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_member.bank_img2
     *
     * @return the value of table_member.bank_img2
     *
     * @mbggenerated
     */
    public String getBankImg2() {
        return bankImg2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_member.bank_img2
     *
     * @param bankImg2 the value for table_member.bank_img2
     *
     * @mbggenerated
     */
    public void setBankImg2(String bankImg2) {
        this.bankImg2 = bankImg2 == null ? null : bankImg2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_member.register_time
     *
     * @return the value of table_member.register_time
     *
     * @mbggenerated
     */
    public Date getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_member.register_time
     *
     * @param registerTime the value for table_member.register_time
     *
     * @mbggenerated
     */
    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_member.last_login_time
     *
     * @return the value of table_member.last_login_time
     *
     * @mbggenerated
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_member.last_login_time
     *
     * @param lastLoginTime the value for table_member.last_login_time
     *
     * @mbggenerated
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_member.perfomance_time
     *
     * @return the value of table_member.perfomance_time
     *
     * @mbggenerated
     */
    public Date getPerfomanceTime() {
        return perfomanceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_member.perfomance_time
     *
     * @param perfomanceTime the value for table_member.perfomance_time
     *
     * @mbggenerated
     */
    public void setPerfomanceTime(Date perfomanceTime) {
        this.perfomanceTime = perfomanceTime;
    }
}