package com.spring.fee.model;

import java.io.Serializable;

public class TableRepurchaseBonusSetting implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_repurchase_bonus_setting.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_repurchase_bonus_setting.price
     *
     * @mbggenerated
     */
    private Float price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_repurchase_bonus_setting.layer
     *
     * @mbggenerated
     */
    private Integer layer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_repurchase_bonus_setting.point
     *
     * @mbggenerated
     */
    private Float point;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table table_repurchase_bonus_setting
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_repurchase_bonus_setting.id
     *
     * @return the value of table_repurchase_bonus_setting.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_repurchase_bonus_setting.id
     *
     * @param id the value for table_repurchase_bonus_setting.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_repurchase_bonus_setting.price
     *
     * @return the value of table_repurchase_bonus_setting.price
     *
     * @mbggenerated
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_repurchase_bonus_setting.price
     *
     * @param price the value for table_repurchase_bonus_setting.price
     *
     * @mbggenerated
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_repurchase_bonus_setting.layer
     *
     * @return the value of table_repurchase_bonus_setting.layer
     *
     * @mbggenerated
     */
    public Integer getLayer() {
        return layer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_repurchase_bonus_setting.layer
     *
     * @param layer the value for table_repurchase_bonus_setting.layer
     *
     * @mbggenerated
     */
    public void setLayer(Integer layer) {
        this.layer = layer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_repurchase_bonus_setting.point
     *
     * @return the value of table_repurchase_bonus_setting.point
     *
     * @mbggenerated
     */
    public Float getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_repurchase_bonus_setting.point
     *
     * @param point the value for table_repurchase_bonus_setting.point
     *
     * @mbggenerated
     */
    public void setPoint(Float point) {
        this.point = point;
    }
}