package com.spring.fee.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class TInvestMemberUpConfigExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_invest_member_up_config
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_invest_member_up_config
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_invest_member_up_config
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_member_up_config
     *
     * @mbggenerated
     */
    public TInvestMemberUpConfigExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_member_up_config
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_member_up_config
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_member_up_config
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_member_up_config
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_member_up_config
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_member_up_config
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_member_up_config
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_member_up_config
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_member_up_config
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_member_up_config
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_invest_member_up_config
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andLevelIdIsNull() {
            addCriterion("level_id is null");
            return (Criteria) this;
        }

        public Criteria andLevelIdIsNotNull() {
            addCriterion("level_id is not null");
            return (Criteria) this;
        }

        public Criteria andLevelIdEqualTo(Integer value) {
            addCriterion("level_id =", value, "levelId");
            return (Criteria) this;
        }

        public Criteria andLevelIdNotEqualTo(Integer value) {
            addCriterion("level_id <>", value, "levelId");
            return (Criteria) this;
        }

        public Criteria andLevelIdGreaterThan(Integer value) {
            addCriterion("level_id >", value, "levelId");
            return (Criteria) this;
        }

        public Criteria andLevelIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("level_id >=", value, "levelId");
            return (Criteria) this;
        }

        public Criteria andLevelIdLessThan(Integer value) {
            addCriterion("level_id <", value, "levelId");
            return (Criteria) this;
        }

        public Criteria andLevelIdLessThanOrEqualTo(Integer value) {
            addCriterion("level_id <=", value, "levelId");
            return (Criteria) this;
        }

        public Criteria andLevelIdIn(List<Integer> values) {
            addCriterion("level_id in", values, "levelId");
            return (Criteria) this;
        }

        public Criteria andLevelIdNotIn(List<Integer> values) {
            addCriterion("level_id not in", values, "levelId");
            return (Criteria) this;
        }

        public Criteria andLevelIdBetween(Integer value1, Integer value2) {
            addCriterion("level_id between", value1, value2, "levelId");
            return (Criteria) this;
        }

        public Criteria andLevelIdNotBetween(Integer value1, Integer value2) {
            addCriterion("level_id not between", value1, value2, "levelId");
            return (Criteria) this;
        }

        public Criteria andLevelNameIsNull() {
            addCriterion("level_name is null");
            return (Criteria) this;
        }

        public Criteria andLevelNameIsNotNull() {
            addCriterion("level_name is not null");
            return (Criteria) this;
        }

        public Criteria andLevelNameEqualTo(String value) {
            addCriterion("level_name =", value, "levelName");
            return (Criteria) this;
        }

        public Criteria andLevelNameNotEqualTo(String value) {
            addCriterion("level_name <>", value, "levelName");
            return (Criteria) this;
        }

        public Criteria andLevelNameGreaterThan(String value) {
            addCriterion("level_name >", value, "levelName");
            return (Criteria) this;
        }

        public Criteria andLevelNameGreaterThanOrEqualTo(String value) {
            addCriterion("level_name >=", value, "levelName");
            return (Criteria) this;
        }

        public Criteria andLevelNameLessThan(String value) {
            addCriterion("level_name <", value, "levelName");
            return (Criteria) this;
        }

        public Criteria andLevelNameLessThanOrEqualTo(String value) {
            addCriterion("level_name <=", value, "levelName");
            return (Criteria) this;
        }

        public Criteria andLevelNameLike(String value) {
            addCriterion("level_name like", value, "levelName");
            return (Criteria) this;
        }

        public Criteria andLevelNameNotLike(String value) {
            addCriterion("level_name not like", value, "levelName");
            return (Criteria) this;
        }

        public Criteria andLevelNameIn(List<String> values) {
            addCriterion("level_name in", values, "levelName");
            return (Criteria) this;
        }

        public Criteria andLevelNameNotIn(List<String> values) {
            addCriterion("level_name not in", values, "levelName");
            return (Criteria) this;
        }

        public Criteria andLevelNameBetween(String value1, String value2) {
            addCriterion("level_name between", value1, value2, "levelName");
            return (Criteria) this;
        }

        public Criteria andLevelNameNotBetween(String value1, String value2) {
            addCriterion("level_name not between", value1, value2, "levelName");
            return (Criteria) this;
        }

        public Criteria andUpTypeIsNull() {
            addCriterion("up_type is null");
            return (Criteria) this;
        }

        public Criteria andUpTypeIsNotNull() {
            addCriterion("up_type is not null");
            return (Criteria) this;
        }

        public Criteria andUpTypeEqualTo(String value) {
            addCriterion("up_type =", value, "upType");
            return (Criteria) this;
        }

        public Criteria andUpTypeNotEqualTo(String value) {
            addCriterion("up_type <>", value, "upType");
            return (Criteria) this;
        }

        public Criteria andUpTypeGreaterThan(String value) {
            addCriterion("up_type >", value, "upType");
            return (Criteria) this;
        }

        public Criteria andUpTypeGreaterThanOrEqualTo(String value) {
            addCriterion("up_type >=", value, "upType");
            return (Criteria) this;
        }

        public Criteria andUpTypeLessThan(String value) {
            addCriterion("up_type <", value, "upType");
            return (Criteria) this;
        }

        public Criteria andUpTypeLessThanOrEqualTo(String value) {
            addCriterion("up_type <=", value, "upType");
            return (Criteria) this;
        }

        public Criteria andUpTypeLike(String value) {
            addCriterion("up_type like", value, "upType");
            return (Criteria) this;
        }

        public Criteria andUpTypeNotLike(String value) {
            addCriterion("up_type not like", value, "upType");
            return (Criteria) this;
        }

        public Criteria andUpTypeIn(List<String> values) {
            addCriterion("up_type in", values, "upType");
            return (Criteria) this;
        }

        public Criteria andUpTypeNotIn(List<String> values) {
            addCriterion("up_type not in", values, "upType");
            return (Criteria) this;
        }

        public Criteria andUpTypeBetween(String value1, String value2) {
            addCriterion("up_type between", value1, value2, "upType");
            return (Criteria) this;
        }

        public Criteria andUpTypeNotBetween(String value1, String value2) {
            addCriterion("up_type not between", value1, value2, "upType");
            return (Criteria) this;
        }

        public Criteria andUpConditionIsNull() {
            addCriterion("up_condition is null");
            return (Criteria) this;
        }

        public Criteria andUpConditionIsNotNull() {
            addCriterion("up_condition is not null");
            return (Criteria) this;
        }

        public Criteria andUpConditionEqualTo(String value) {
            addCriterion("up_condition =", value, "upCondition");
            return (Criteria) this;
        }

        public Criteria andUpConditionNotEqualTo(String value) {
            addCriterion("up_condition <>", value, "upCondition");
            return (Criteria) this;
        }

        public Criteria andUpConditionGreaterThan(String value) {
            addCriterion("up_condition >", value, "upCondition");
            return (Criteria) this;
        }

        public Criteria andUpConditionGreaterThanOrEqualTo(String value) {
            addCriterion("up_condition >=", value, "upCondition");
            return (Criteria) this;
        }

        public Criteria andUpConditionLessThan(String value) {
            addCriterion("up_condition <", value, "upCondition");
            return (Criteria) this;
        }

        public Criteria andUpConditionLessThanOrEqualTo(String value) {
            addCriterion("up_condition <=", value, "upCondition");
            return (Criteria) this;
        }

        public Criteria andUpConditionLike(String value) {
            addCriterion("up_condition like", value, "upCondition");
            return (Criteria) this;
        }

        public Criteria andUpConditionNotLike(String value) {
            addCriterion("up_condition not like", value, "upCondition");
            return (Criteria) this;
        }

        public Criteria andUpConditionIn(List<String> values) {
            addCriterion("up_condition in", values, "upCondition");
            return (Criteria) this;
        }

        public Criteria andUpConditionNotIn(List<String> values) {
            addCriterion("up_condition not in", values, "upCondition");
            return (Criteria) this;
        }

        public Criteria andUpConditionBetween(String value1, String value2) {
            addCriterion("up_condition between", value1, value2, "upCondition");
            return (Criteria) this;
        }

        public Criteria andUpConditionNotBetween(String value1, String value2) {
            addCriterion("up_condition not between", value1, value2, "upCondition");
            return (Criteria) this;
        }

        public Criteria andConditionXIsNull() {
            addCriterion("condition_x is null");
            return (Criteria) this;
        }

        public Criteria andConditionXIsNotNull() {
            addCriterion("condition_x is not null");
            return (Criteria) this;
        }

        public Criteria andConditionXEqualTo(Long value) {
            addCriterion("condition_x =", value, "conditionX");
            return (Criteria) this;
        }

        public Criteria andConditionXNotEqualTo(Long value) {
            addCriterion("condition_x <>", value, "conditionX");
            return (Criteria) this;
        }

        public Criteria andConditionXGreaterThan(Long value) {
            addCriterion("condition_x >", value, "conditionX");
            return (Criteria) this;
        }

        public Criteria andConditionXGreaterThanOrEqualTo(Long value) {
            addCriterion("condition_x >=", value, "conditionX");
            return (Criteria) this;
        }

        public Criteria andConditionXLessThan(Long value) {
            addCriterion("condition_x <", value, "conditionX");
            return (Criteria) this;
        }

        public Criteria andConditionXLessThanOrEqualTo(Long value) {
            addCriterion("condition_x <=", value, "conditionX");
            return (Criteria) this;
        }

        public Criteria andConditionXIn(List<Long> values) {
            addCriterion("condition_x in", values, "conditionX");
            return (Criteria) this;
        }

        public Criteria andConditionXNotIn(List<Long> values) {
            addCriterion("condition_x not in", values, "conditionX");
            return (Criteria) this;
        }

        public Criteria andConditionXBetween(Long value1, Long value2) {
            addCriterion("condition_x between", value1, value2, "conditionX");
            return (Criteria) this;
        }

        public Criteria andConditionXNotBetween(Long value1, Long value2) {
            addCriterion("condition_x not between", value1, value2, "conditionX");
            return (Criteria) this;
        }

        public Criteria andConditionYIsNull() {
            addCriterion("condition_y is null");
            return (Criteria) this;
        }

        public Criteria andConditionYIsNotNull() {
            addCriterion("condition_y is not null");
            return (Criteria) this;
        }

        public Criteria andConditionYEqualTo(Integer value) {
            addCriterion("condition_y =", value, "conditionY");
            return (Criteria) this;
        }

        public Criteria andConditionYNotEqualTo(Integer value) {
            addCriterion("condition_y <>", value, "conditionY");
            return (Criteria) this;
        }

        public Criteria andConditionYGreaterThan(Integer value) {
            addCriterion("condition_y >", value, "conditionY");
            return (Criteria) this;
        }

        public Criteria andConditionYGreaterThanOrEqualTo(Integer value) {
            addCriterion("condition_y >=", value, "conditionY");
            return (Criteria) this;
        }

        public Criteria andConditionYLessThan(Integer value) {
            addCriterion("condition_y <", value, "conditionY");
            return (Criteria) this;
        }

        public Criteria andConditionYLessThanOrEqualTo(Integer value) {
            addCriterion("condition_y <=", value, "conditionY");
            return (Criteria) this;
        }

        public Criteria andConditionYIn(List<Integer> values) {
            addCriterion("condition_y in", values, "conditionY");
            return (Criteria) this;
        }

        public Criteria andConditionYNotIn(List<Integer> values) {
            addCriterion("condition_y not in", values, "conditionY");
            return (Criteria) this;
        }

        public Criteria andConditionYBetween(Integer value1, Integer value2) {
            addCriterion("condition_y between", value1, value2, "conditionY");
            return (Criteria) this;
        }

        public Criteria andConditionYNotBetween(Integer value1, Integer value2) {
            addCriterion("condition_y not between", value1, value2, "conditionY");
            return (Criteria) this;
        }

        public Criteria andPerformancePersentIsNull() {
            addCriterion("performance_persent is null");
            return (Criteria) this;
        }

        public Criteria andPerformancePersentIsNotNull() {
            addCriterion("performance_persent is not null");
            return (Criteria) this;
        }

        public Criteria andPerformancePersentEqualTo(BigDecimal value) {
            addCriterion("performance_persent =", value, "performancePersent");
            return (Criteria) this;
        }

        public Criteria andPerformancePersentNotEqualTo(BigDecimal value) {
            addCriterion("performance_persent <>", value, "performancePersent");
            return (Criteria) this;
        }

        public Criteria andPerformancePersentGreaterThan(BigDecimal value) {
            addCriterion("performance_persent >", value, "performancePersent");
            return (Criteria) this;
        }

        public Criteria andPerformancePersentGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("performance_persent >=", value, "performancePersent");
            return (Criteria) this;
        }

        public Criteria andPerformancePersentLessThan(BigDecimal value) {
            addCriterion("performance_persent <", value, "performancePersent");
            return (Criteria) this;
        }

        public Criteria andPerformancePersentLessThanOrEqualTo(BigDecimal value) {
            addCriterion("performance_persent <=", value, "performancePersent");
            return (Criteria) this;
        }

        public Criteria andPerformancePersentIn(List<BigDecimal> values) {
            addCriterion("performance_persent in", values, "performancePersent");
            return (Criteria) this;
        }

        public Criteria andPerformancePersentNotIn(List<BigDecimal> values) {
            addCriterion("performance_persent not in", values, "performancePersent");
            return (Criteria) this;
        }

        public Criteria andPerformancePersentBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("performance_persent between", value1, value2, "performancePersent");
            return (Criteria) this;
        }

        public Criteria andPerformancePersentNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("performance_persent not between", value1, value2, "performancePersent");
            return (Criteria) this;
        }

        public Criteria andCommissionPersentIsNull() {
            addCriterion("commission_persent is null");
            return (Criteria) this;
        }

        public Criteria andCommissionPersentIsNotNull() {
            addCriterion("commission_persent is not null");
            return (Criteria) this;
        }

        public Criteria andCommissionPersentEqualTo(BigDecimal value) {
            addCriterion("commission_persent =", value, "commissionPersent");
            return (Criteria) this;
        }

        public Criteria andCommissionPersentNotEqualTo(BigDecimal value) {
            addCriterion("commission_persent <>", value, "commissionPersent");
            return (Criteria) this;
        }

        public Criteria andCommissionPersentGreaterThan(BigDecimal value) {
            addCriterion("commission_persent >", value, "commissionPersent");
            return (Criteria) this;
        }

        public Criteria andCommissionPersentGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("commission_persent >=", value, "commissionPersent");
            return (Criteria) this;
        }

        public Criteria andCommissionPersentLessThan(BigDecimal value) {
            addCriterion("commission_persent <", value, "commissionPersent");
            return (Criteria) this;
        }

        public Criteria andCommissionPersentLessThanOrEqualTo(BigDecimal value) {
            addCriterion("commission_persent <=", value, "commissionPersent");
            return (Criteria) this;
        }

        public Criteria andCommissionPersentIn(List<BigDecimal> values) {
            addCriterion("commission_persent in", values, "commissionPersent");
            return (Criteria) this;
        }

        public Criteria andCommissionPersentNotIn(List<BigDecimal> values) {
            addCriterion("commission_persent not in", values, "commissionPersent");
            return (Criteria) this;
        }

        public Criteria andCommissionPersentBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("commission_persent between", value1, value2, "commissionPersent");
            return (Criteria) this;
        }

        public Criteria andCommissionPersentNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("commission_persent not between", value1, value2, "commissionPersent");
            return (Criteria) this;
        }

        public Criteria andSharingPersentIsNull() {
            addCriterion("sharing_persent is null");
            return (Criteria) this;
        }

        public Criteria andSharingPersentIsNotNull() {
            addCriterion("sharing_persent is not null");
            return (Criteria) this;
        }

        public Criteria andSharingPersentEqualTo(BigDecimal value) {
            addCriterion("sharing_persent =", value, "sharingPersent");
            return (Criteria) this;
        }

        public Criteria andSharingPersentNotEqualTo(BigDecimal value) {
            addCriterion("sharing_persent <>", value, "sharingPersent");
            return (Criteria) this;
        }

        public Criteria andSharingPersentGreaterThan(BigDecimal value) {
            addCriterion("sharing_persent >", value, "sharingPersent");
            return (Criteria) this;
        }

        public Criteria andSharingPersentGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("sharing_persent >=", value, "sharingPersent");
            return (Criteria) this;
        }

        public Criteria andSharingPersentLessThan(BigDecimal value) {
            addCriterion("sharing_persent <", value, "sharingPersent");
            return (Criteria) this;
        }

        public Criteria andSharingPersentLessThanOrEqualTo(BigDecimal value) {
            addCriterion("sharing_persent <=", value, "sharingPersent");
            return (Criteria) this;
        }

        public Criteria andSharingPersentIn(List<BigDecimal> values) {
            addCriterion("sharing_persent in", values, "sharingPersent");
            return (Criteria) this;
        }

        public Criteria andSharingPersentNotIn(List<BigDecimal> values) {
            addCriterion("sharing_persent not in", values, "sharingPersent");
            return (Criteria) this;
        }

        public Criteria andSharingPersentBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sharing_persent between", value1, value2, "sharingPersent");
            return (Criteria) this;
        }

        public Criteria andSharingPersentNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sharing_persent not between", value1, value2, "sharingPersent");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_invest_member_up_config
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_invest_member_up_config
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}