package com.spring.fee.model;

import java.util.ArrayList;
import java.util.List;

public class TInvestPlanConfigExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_invest_plan_config
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_invest_plan_config
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_invest_plan_config
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_plan_config
     *
     * @mbggenerated
     */
    public TInvestPlanConfigExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_plan_config
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_plan_config
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_plan_config
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_plan_config
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_plan_config
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_plan_config
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_plan_config
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_plan_config
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_plan_config
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_plan_config
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_invest_plan_config
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPlanIdIsNull() {
            addCriterion("plan_id is null");
            return (Criteria) this;
        }

        public Criteria andPlanIdIsNotNull() {
            addCriterion("plan_id is not null");
            return (Criteria) this;
        }

        public Criteria andPlanIdEqualTo(String value) {
            addCriterion("plan_id =", value, "planId");
            return (Criteria) this;
        }

        public Criteria andPlanIdNotEqualTo(String value) {
            addCriterion("plan_id <>", value, "planId");
            return (Criteria) this;
        }

        public Criteria andPlanIdGreaterThan(String value) {
            addCriterion("plan_id >", value, "planId");
            return (Criteria) this;
        }

        public Criteria andPlanIdGreaterThanOrEqualTo(String value) {
            addCriterion("plan_id >=", value, "planId");
            return (Criteria) this;
        }

        public Criteria andPlanIdLessThan(String value) {
            addCriterion("plan_id <", value, "planId");
            return (Criteria) this;
        }

        public Criteria andPlanIdLessThanOrEqualTo(String value) {
            addCriterion("plan_id <=", value, "planId");
            return (Criteria) this;
        }

        public Criteria andPlanIdLike(String value) {
            addCriterion("plan_id like", value, "planId");
            return (Criteria) this;
        }

        public Criteria andPlanIdNotLike(String value) {
            addCriterion("plan_id not like", value, "planId");
            return (Criteria) this;
        }

        public Criteria andPlanIdIn(List<String> values) {
            addCriterion("plan_id in", values, "planId");
            return (Criteria) this;
        }

        public Criteria andPlanIdNotIn(List<String> values) {
            addCriterion("plan_id not in", values, "planId");
            return (Criteria) this;
        }

        public Criteria andPlanIdBetween(String value1, String value2) {
            addCriterion("plan_id between", value1, value2, "planId");
            return (Criteria) this;
        }

        public Criteria andPlanIdNotBetween(String value1, String value2) {
            addCriterion("plan_id not between", value1, value2, "planId");
            return (Criteria) this;
        }

        public Criteria andPlanNameIsNull() {
            addCriterion("plan_name is null");
            return (Criteria) this;
        }

        public Criteria andPlanNameIsNotNull() {
            addCriterion("plan_name is not null");
            return (Criteria) this;
        }

        public Criteria andPlanNameEqualTo(String value) {
            addCriterion("plan_name =", value, "planName");
            return (Criteria) this;
        }

        public Criteria andPlanNameNotEqualTo(String value) {
            addCriterion("plan_name <>", value, "planName");
            return (Criteria) this;
        }

        public Criteria andPlanNameGreaterThan(String value) {
            addCriterion("plan_name >", value, "planName");
            return (Criteria) this;
        }

        public Criteria andPlanNameGreaterThanOrEqualTo(String value) {
            addCriterion("plan_name >=", value, "planName");
            return (Criteria) this;
        }

        public Criteria andPlanNameLessThan(String value) {
            addCriterion("plan_name <", value, "planName");
            return (Criteria) this;
        }

        public Criteria andPlanNameLessThanOrEqualTo(String value) {
            addCriterion("plan_name <=", value, "planName");
            return (Criteria) this;
        }

        public Criteria andPlanNameLike(String value) {
            addCriterion("plan_name like", value, "planName");
            return (Criteria) this;
        }

        public Criteria andPlanNameNotLike(String value) {
            addCriterion("plan_name not like", value, "planName");
            return (Criteria) this;
        }

        public Criteria andPlanNameIn(List<String> values) {
            addCriterion("plan_name in", values, "planName");
            return (Criteria) this;
        }

        public Criteria andPlanNameNotIn(List<String> values) {
            addCriterion("plan_name not in", values, "planName");
            return (Criteria) this;
        }

        public Criteria andPlanNameBetween(String value1, String value2) {
            addCriterion("plan_name between", value1, value2, "planName");
            return (Criteria) this;
        }

        public Criteria andPlanNameNotBetween(String value1, String value2) {
            addCriterion("plan_name not between", value1, value2, "planName");
            return (Criteria) this;
        }

        public Criteria andPlanAmountIsNull() {
            addCriterion("plan_amount is null");
            return (Criteria) this;
        }

        public Criteria andPlanAmountIsNotNull() {
            addCriterion("plan_amount is not null");
            return (Criteria) this;
        }

        public Criteria andPlanAmountEqualTo(Long value) {
            addCriterion("plan_amount =", value, "planAmount");
            return (Criteria) this;
        }

        public Criteria andPlanAmountNotEqualTo(Long value) {
            addCriterion("plan_amount <>", value, "planAmount");
            return (Criteria) this;
        }

        public Criteria andPlanAmountGreaterThan(Long value) {
            addCriterion("plan_amount >", value, "planAmount");
            return (Criteria) this;
        }

        public Criteria andPlanAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("plan_amount >=", value, "planAmount");
            return (Criteria) this;
        }

        public Criteria andPlanAmountLessThan(Long value) {
            addCriterion("plan_amount <", value, "planAmount");
            return (Criteria) this;
        }

        public Criteria andPlanAmountLessThanOrEqualTo(Long value) {
            addCriterion("plan_amount <=", value, "planAmount");
            return (Criteria) this;
        }

        public Criteria andPlanAmountIn(List<Long> values) {
            addCriterion("plan_amount in", values, "planAmount");
            return (Criteria) this;
        }

        public Criteria andPlanAmountNotIn(List<Long> values) {
            addCriterion("plan_amount not in", values, "planAmount");
            return (Criteria) this;
        }

        public Criteria andPlanAmountBetween(Long value1, Long value2) {
            addCriterion("plan_amount between", value1, value2, "planAmount");
            return (Criteria) this;
        }

        public Criteria andPlanAmountNotBetween(Long value1, Long value2) {
            addCriterion("plan_amount not between", value1, value2, "planAmount");
            return (Criteria) this;
        }

        public Criteria andPlanDaysIsNull() {
            addCriterion("plan_days is null");
            return (Criteria) this;
        }

        public Criteria andPlanDaysIsNotNull() {
            addCriterion("plan_days is not null");
            return (Criteria) this;
        }

        public Criteria andPlanDaysEqualTo(Integer value) {
            addCriterion("plan_days =", value, "planDays");
            return (Criteria) this;
        }

        public Criteria andPlanDaysNotEqualTo(Integer value) {
            addCriterion("plan_days <>", value, "planDays");
            return (Criteria) this;
        }

        public Criteria andPlanDaysGreaterThan(Integer value) {
            addCriterion("plan_days >", value, "planDays");
            return (Criteria) this;
        }

        public Criteria andPlanDaysGreaterThanOrEqualTo(Integer value) {
            addCriterion("plan_days >=", value, "planDays");
            return (Criteria) this;
        }

        public Criteria andPlanDaysLessThan(Integer value) {
            addCriterion("plan_days <", value, "planDays");
            return (Criteria) this;
        }

        public Criteria andPlanDaysLessThanOrEqualTo(Integer value) {
            addCriterion("plan_days <=", value, "planDays");
            return (Criteria) this;
        }

        public Criteria andPlanDaysIn(List<Integer> values) {
            addCriterion("plan_days in", values, "planDays");
            return (Criteria) this;
        }

        public Criteria andPlanDaysNotIn(List<Integer> values) {
            addCriterion("plan_days not in", values, "planDays");
            return (Criteria) this;
        }

        public Criteria andPlanDaysBetween(Integer value1, Integer value2) {
            addCriterion("plan_days between", value1, value2, "planDays");
            return (Criteria) this;
        }

        public Criteria andPlanDaysNotBetween(Integer value1, Integer value2) {
            addCriterion("plan_days not between", value1, value2, "planDays");
            return (Criteria) this;
        }

        public Criteria andMainAmountIsNull() {
            addCriterion("main_amount is null");
            return (Criteria) this;
        }

        public Criteria andMainAmountIsNotNull() {
            addCriterion("main_amount is not null");
            return (Criteria) this;
        }

        public Criteria andMainAmountEqualTo(Long value) {
            addCriterion("main_amount =", value, "mainAmount");
            return (Criteria) this;
        }

        public Criteria andMainAmountNotEqualTo(Long value) {
            addCriterion("main_amount <>", value, "mainAmount");
            return (Criteria) this;
        }

        public Criteria andMainAmountGreaterThan(Long value) {
            addCriterion("main_amount >", value, "mainAmount");
            return (Criteria) this;
        }

        public Criteria andMainAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("main_amount >=", value, "mainAmount");
            return (Criteria) this;
        }

        public Criteria andMainAmountLessThan(Long value) {
            addCriterion("main_amount <", value, "mainAmount");
            return (Criteria) this;
        }

        public Criteria andMainAmountLessThanOrEqualTo(Long value) {
            addCriterion("main_amount <=", value, "mainAmount");
            return (Criteria) this;
        }

        public Criteria andMainAmountIn(List<Long> values) {
            addCriterion("main_amount in", values, "mainAmount");
            return (Criteria) this;
        }

        public Criteria andMainAmountNotIn(List<Long> values) {
            addCriterion("main_amount not in", values, "mainAmount");
            return (Criteria) this;
        }

        public Criteria andMainAmountBetween(Long value1, Long value2) {
            addCriterion("main_amount between", value1, value2, "mainAmount");
            return (Criteria) this;
        }

        public Criteria andMainAmountNotBetween(Long value1, Long value2) {
            addCriterion("main_amount not between", value1, value2, "mainAmount");
            return (Criteria) this;
        }

        public Criteria andMainDaysIsNull() {
            addCriterion("main_days is null");
            return (Criteria) this;
        }

        public Criteria andMainDaysIsNotNull() {
            addCriterion("main_days is not null");
            return (Criteria) this;
        }

        public Criteria andMainDaysEqualTo(Integer value) {
            addCriterion("main_days =", value, "mainDays");
            return (Criteria) this;
        }

        public Criteria andMainDaysNotEqualTo(Integer value) {
            addCriterion("main_days <>", value, "mainDays");
            return (Criteria) this;
        }

        public Criteria andMainDaysGreaterThan(Integer value) {
            addCriterion("main_days >", value, "mainDays");
            return (Criteria) this;
        }

        public Criteria andMainDaysGreaterThanOrEqualTo(Integer value) {
            addCriterion("main_days >=", value, "mainDays");
            return (Criteria) this;
        }

        public Criteria andMainDaysLessThan(Integer value) {
            addCriterion("main_days <", value, "mainDays");
            return (Criteria) this;
        }

        public Criteria andMainDaysLessThanOrEqualTo(Integer value) {
            addCriterion("main_days <=", value, "mainDays");
            return (Criteria) this;
        }

        public Criteria andMainDaysIn(List<Integer> values) {
            addCriterion("main_days in", values, "mainDays");
            return (Criteria) this;
        }

        public Criteria andMainDaysNotIn(List<Integer> values) {
            addCriterion("main_days not in", values, "mainDays");
            return (Criteria) this;
        }

        public Criteria andMainDaysBetween(Integer value1, Integer value2) {
            addCriterion("main_days between", value1, value2, "mainDays");
            return (Criteria) this;
        }

        public Criteria andMainDaysNotBetween(Integer value1, Integer value2) {
            addCriterion("main_days not between", value1, value2, "mainDays");
            return (Criteria) this;
        }

        public Criteria andSecondAmountIsNull() {
            addCriterion("second_amount is null");
            return (Criteria) this;
        }

        public Criteria andSecondAmountIsNotNull() {
            addCriterion("second_amount is not null");
            return (Criteria) this;
        }

        public Criteria andSecondAmountEqualTo(Long value) {
            addCriterion("second_amount =", value, "secondAmount");
            return (Criteria) this;
        }

        public Criteria andSecondAmountNotEqualTo(Long value) {
            addCriterion("second_amount <>", value, "secondAmount");
            return (Criteria) this;
        }

        public Criteria andSecondAmountGreaterThan(Long value) {
            addCriterion("second_amount >", value, "secondAmount");
            return (Criteria) this;
        }

        public Criteria andSecondAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("second_amount >=", value, "secondAmount");
            return (Criteria) this;
        }

        public Criteria andSecondAmountLessThan(Long value) {
            addCriterion("second_amount <", value, "secondAmount");
            return (Criteria) this;
        }

        public Criteria andSecondAmountLessThanOrEqualTo(Long value) {
            addCriterion("second_amount <=", value, "secondAmount");
            return (Criteria) this;
        }

        public Criteria andSecondAmountIn(List<Long> values) {
            addCriterion("second_amount in", values, "secondAmount");
            return (Criteria) this;
        }

        public Criteria andSecondAmountNotIn(List<Long> values) {
            addCriterion("second_amount not in", values, "secondAmount");
            return (Criteria) this;
        }

        public Criteria andSecondAmountBetween(Long value1, Long value2) {
            addCriterion("second_amount between", value1, value2, "secondAmount");
            return (Criteria) this;
        }

        public Criteria andSecondAmountNotBetween(Long value1, Long value2) {
            addCriterion("second_amount not between", value1, value2, "secondAmount");
            return (Criteria) this;
        }

        public Criteria andSecondDaysIsNull() {
            addCriterion("second_days is null");
            return (Criteria) this;
        }

        public Criteria andSecondDaysIsNotNull() {
            addCriterion("second_days is not null");
            return (Criteria) this;
        }

        public Criteria andSecondDaysEqualTo(Integer value) {
            addCriterion("second_days =", value, "secondDays");
            return (Criteria) this;
        }

        public Criteria andSecondDaysNotEqualTo(Integer value) {
            addCriterion("second_days <>", value, "secondDays");
            return (Criteria) this;
        }

        public Criteria andSecondDaysGreaterThan(Integer value) {
            addCriterion("second_days >", value, "secondDays");
            return (Criteria) this;
        }

        public Criteria andSecondDaysGreaterThanOrEqualTo(Integer value) {
            addCriterion("second_days >=", value, "secondDays");
            return (Criteria) this;
        }

        public Criteria andSecondDaysLessThan(Integer value) {
            addCriterion("second_days <", value, "secondDays");
            return (Criteria) this;
        }

        public Criteria andSecondDaysLessThanOrEqualTo(Integer value) {
            addCriterion("second_days <=", value, "secondDays");
            return (Criteria) this;
        }

        public Criteria andSecondDaysIn(List<Integer> values) {
            addCriterion("second_days in", values, "secondDays");
            return (Criteria) this;
        }

        public Criteria andSecondDaysNotIn(List<Integer> values) {
            addCriterion("second_days not in", values, "secondDays");
            return (Criteria) this;
        }

        public Criteria andSecondDaysBetween(Integer value1, Integer value2) {
            addCriterion("second_days between", value1, value2, "secondDays");
            return (Criteria) this;
        }

        public Criteria andSecondDaysNotBetween(Integer value1, Integer value2) {
            addCriterion("second_days not between", value1, value2, "secondDays");
            return (Criteria) this;
        }

        public Criteria andMaxCountIsNull() {
            addCriterion("max_count is null");
            return (Criteria) this;
        }

        public Criteria andMaxCountIsNotNull() {
            addCriterion("max_count is not null");
            return (Criteria) this;
        }

        public Criteria andMaxCountEqualTo(Integer value) {
            addCriterion("max_count =", value, "maxCount");
            return (Criteria) this;
        }

        public Criteria andMaxCountNotEqualTo(Integer value) {
            addCriterion("max_count <>", value, "maxCount");
            return (Criteria) this;
        }

        public Criteria andMaxCountGreaterThan(Integer value) {
            addCriterion("max_count >", value, "maxCount");
            return (Criteria) this;
        }

        public Criteria andMaxCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("max_count >=", value, "maxCount");
            return (Criteria) this;
        }

        public Criteria andMaxCountLessThan(Integer value) {
            addCriterion("max_count <", value, "maxCount");
            return (Criteria) this;
        }

        public Criteria andMaxCountLessThanOrEqualTo(Integer value) {
            addCriterion("max_count <=", value, "maxCount");
            return (Criteria) this;
        }

        public Criteria andMaxCountIn(List<Integer> values) {
            addCriterion("max_count in", values, "maxCount");
            return (Criteria) this;
        }

        public Criteria andMaxCountNotIn(List<Integer> values) {
            addCriterion("max_count not in", values, "maxCount");
            return (Criteria) this;
        }

        public Criteria andMaxCountBetween(Integer value1, Integer value2) {
            addCriterion("max_count between", value1, value2, "maxCount");
            return (Criteria) this;
        }

        public Criteria andMaxCountNotBetween(Integer value1, Integer value2) {
            addCriterion("max_count not between", value1, value2, "maxCount");
            return (Criteria) this;
        }

        public Criteria andInterestReturnPerIsNull() {
            addCriterion("interest_return_per is null");
            return (Criteria) this;
        }

        public Criteria andInterestReturnPerIsNotNull() {
            addCriterion("interest_return_per is not null");
            return (Criteria) this;
        }

        public Criteria andInterestReturnPerEqualTo(Double value) {
            addCriterion("interest_return_per =", value, "interestReturnPer");
            return (Criteria) this;
        }

        public Criteria andInterestReturnPerNotEqualTo(Double value) {
            addCriterion("interest_return_per <>", value, "interestReturnPer");
            return (Criteria) this;
        }

        public Criteria andInterestReturnPerGreaterThan(Double value) {
            addCriterion("interest_return_per >", value, "interestReturnPer");
            return (Criteria) this;
        }

        public Criteria andInterestReturnPerGreaterThanOrEqualTo(Double value) {
            addCriterion("interest_return_per >=", value, "interestReturnPer");
            return (Criteria) this;
        }

        public Criteria andInterestReturnPerLessThan(Double value) {
            addCriterion("interest_return_per <", value, "interestReturnPer");
            return (Criteria) this;
        }

        public Criteria andInterestReturnPerLessThanOrEqualTo(Double value) {
            addCriterion("interest_return_per <=", value, "interestReturnPer");
            return (Criteria) this;
        }

        public Criteria andInterestReturnPerIn(List<Double> values) {
            addCriterion("interest_return_per in", values, "interestReturnPer");
            return (Criteria) this;
        }

        public Criteria andInterestReturnPerNotIn(List<Double> values) {
            addCriterion("interest_return_per not in", values, "interestReturnPer");
            return (Criteria) this;
        }

        public Criteria andInterestReturnPerBetween(Double value1, Double value2) {
            addCriterion("interest_return_per between", value1, value2, "interestReturnPer");
            return (Criteria) this;
        }

        public Criteria andInterestReturnPerNotBetween(Double value1, Double value2) {
            addCriterion("interest_return_per not between", value1, value2, "interestReturnPer");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_invest_plan_config
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_invest_plan_config
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}