package com.spring.fee.model;

import java.io.Serializable;
import java.util.Date;

public class TInvestPlanMain implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invest_plan_main.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invest_plan_main.order_id
     *
     * @mbggenerated
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invest_plan_main.plan_id
     *
     * @mbggenerated
     */
    private String planId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invest_plan_main.member_id
     *
     * @mbggenerated
     */
    private String memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invest_plan_main.plan_name
     *
     * @mbggenerated
     */
    private String planName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invest_plan_main.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invest_plan_main.status_time
     *
     * @mbggenerated
     */
    private Date statusTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invest_plan_main.total_amount
     *
     * @mbggenerated
     */
    private Long totalAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invest_plan_main.total_days
     *
     * @mbggenerated
     */
    private Integer totalDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invest_plan_main.plan_amount
     *
     * @mbggenerated
     */
    private Long planAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invest_plan_main.plan_days
     *
     * @mbggenerated
     */
    private Integer planDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invest_plan_main.append_flay
     *
     * @mbggenerated
     */
    private String appendFlay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invest_plan_main.start_yyyymmdd
     *
     * @mbggenerated
     */
    private String startYyyymmdd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invest_plan_main.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invest_plan_main.settle_yyyymmdd
     *
     * @mbggenerated
     */
    private String settleYyyymmdd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invest_plan_main.start_time
     *
     * @mbggenerated
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invest_plan_main.end_time
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invest_plan_main.interest_return_per
     *
     * @mbggenerated
     */
    private Double interestReturnPer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invest_plan_main.be_append_flay
     *
     * @mbggenerated
     */
    private String beAppendFlay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_invest_plan_main
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invest_plan_main.id
     *
     * @return the value of t_invest_plan_main.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invest_plan_main.id
     *
     * @param id the value for t_invest_plan_main.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invest_plan_main.order_id
     *
     * @return the value of t_invest_plan_main.order_id
     *
     * @mbggenerated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invest_plan_main.order_id
     *
     * @param orderId the value for t_invest_plan_main.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invest_plan_main.plan_id
     *
     * @return the value of t_invest_plan_main.plan_id
     *
     * @mbggenerated
     */
    public String getPlanId() {
        return planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invest_plan_main.plan_id
     *
     * @param planId the value for t_invest_plan_main.plan_id
     *
     * @mbggenerated
     */
    public void setPlanId(String planId) {
        this.planId = planId == null ? null : planId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invest_plan_main.member_id
     *
     * @return the value of t_invest_plan_main.member_id
     *
     * @mbggenerated
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invest_plan_main.member_id
     *
     * @param memberId the value for t_invest_plan_main.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId == null ? null : memberId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invest_plan_main.plan_name
     *
     * @return the value of t_invest_plan_main.plan_name
     *
     * @mbggenerated
     */
    public String getPlanName() {
        return planName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invest_plan_main.plan_name
     *
     * @param planName the value for t_invest_plan_main.plan_name
     *
     * @mbggenerated
     */
    public void setPlanName(String planName) {
        this.planName = planName == null ? null : planName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invest_plan_main.status
     *
     * @return the value of t_invest_plan_main.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invest_plan_main.status
     *
     * @param status the value for t_invest_plan_main.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invest_plan_main.status_time
     *
     * @return the value of t_invest_plan_main.status_time
     *
     * @mbggenerated
     */
    public Date getStatusTime() {
        return statusTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invest_plan_main.status_time
     *
     * @param statusTime the value for t_invest_plan_main.status_time
     *
     * @mbggenerated
     */
    public void setStatusTime(Date statusTime) {
        this.statusTime = statusTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invest_plan_main.total_amount
     *
     * @return the value of t_invest_plan_main.total_amount
     *
     * @mbggenerated
     */
    public Long getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invest_plan_main.total_amount
     *
     * @param totalAmount the value for t_invest_plan_main.total_amount
     *
     * @mbggenerated
     */
    public void setTotalAmount(Long totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invest_plan_main.total_days
     *
     * @return the value of t_invest_plan_main.total_days
     *
     * @mbggenerated
     */
    public Integer getTotalDays() {
        return totalDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invest_plan_main.total_days
     *
     * @param totalDays the value for t_invest_plan_main.total_days
     *
     * @mbggenerated
     */
    public void setTotalDays(Integer totalDays) {
        this.totalDays = totalDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invest_plan_main.plan_amount
     *
     * @return the value of t_invest_plan_main.plan_amount
     *
     * @mbggenerated
     */
    public Long getPlanAmount() {
        return planAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invest_plan_main.plan_amount
     *
     * @param planAmount the value for t_invest_plan_main.plan_amount
     *
     * @mbggenerated
     */
    public void setPlanAmount(Long planAmount) {
        this.planAmount = planAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invest_plan_main.plan_days
     *
     * @return the value of t_invest_plan_main.plan_days
     *
     * @mbggenerated
     */
    public Integer getPlanDays() {
        return planDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invest_plan_main.plan_days
     *
     * @param planDays the value for t_invest_plan_main.plan_days
     *
     * @mbggenerated
     */
    public void setPlanDays(Integer planDays) {
        this.planDays = planDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invest_plan_main.append_flay
     *
     * @return the value of t_invest_plan_main.append_flay
     *
     * @mbggenerated
     */
    public String getAppendFlay() {
        return appendFlay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invest_plan_main.append_flay
     *
     * @param appendFlay the value for t_invest_plan_main.append_flay
     *
     * @mbggenerated
     */
    public void setAppendFlay(String appendFlay) {
        this.appendFlay = appendFlay == null ? null : appendFlay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invest_plan_main.start_yyyymmdd
     *
     * @return the value of t_invest_plan_main.start_yyyymmdd
     *
     * @mbggenerated
     */
    public String getStartYyyymmdd() {
        return startYyyymmdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invest_plan_main.start_yyyymmdd
     *
     * @param startYyyymmdd the value for t_invest_plan_main.start_yyyymmdd
     *
     * @mbggenerated
     */
    public void setStartYyyymmdd(String startYyyymmdd) {
        this.startYyyymmdd = startYyyymmdd == null ? null : startYyyymmdd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invest_plan_main.create_time
     *
     * @return the value of t_invest_plan_main.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invest_plan_main.create_time
     *
     * @param createTime the value for t_invest_plan_main.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invest_plan_main.settle_yyyymmdd
     *
     * @return the value of t_invest_plan_main.settle_yyyymmdd
     *
     * @mbggenerated
     */
    public String getSettleYyyymmdd() {
        return settleYyyymmdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invest_plan_main.settle_yyyymmdd
     *
     * @param settleYyyymmdd the value for t_invest_plan_main.settle_yyyymmdd
     *
     * @mbggenerated
     */
    public void setSettleYyyymmdd(String settleYyyymmdd) {
        this.settleYyyymmdd = settleYyyymmdd == null ? null : settleYyyymmdd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invest_plan_main.start_time
     *
     * @return the value of t_invest_plan_main.start_time
     *
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invest_plan_main.start_time
     *
     * @param startTime the value for t_invest_plan_main.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invest_plan_main.end_time
     *
     * @return the value of t_invest_plan_main.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invest_plan_main.end_time
     *
     * @param endTime the value for t_invest_plan_main.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invest_plan_main.interest_return_per
     *
     * @return the value of t_invest_plan_main.interest_return_per
     *
     * @mbggenerated
     */
    public Double getInterestReturnPer() {
        return interestReturnPer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invest_plan_main.interest_return_per
     *
     * @param interestReturnPer the value for t_invest_plan_main.interest_return_per
     *
     * @mbggenerated
     */
    public void setInterestReturnPer(Double interestReturnPer) {
        this.interestReturnPer = interestReturnPer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invest_plan_main.be_append_flay
     *
     * @return the value of t_invest_plan_main.be_append_flay
     *
     * @mbggenerated
     */
    public String getBeAppendFlay() {
        return beAppendFlay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invest_plan_main.be_append_flay
     *
     * @param beAppendFlay the value for t_invest_plan_main.be_append_flay
     *
     * @mbggenerated
     */
    public void setBeAppendFlay(String beAppendFlay) {
        this.beAppendFlay = beAppendFlay == null ? null : beAppendFlay.trim();
    }
}