package com.spring.fee.model;

import java.io.Serializable;
import java.util.Date;

public class TInvestQueue implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invest_queue.order_id
     *
     * @mbggenerated
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invest_queue.orig_plan_main_id
     *
     * @mbggenerated
     */
    private String origPlanMainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invest_queue.plan_id
     *
     * @mbggenerated
     */
    private String planId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invest_queue.member_id
     *
     * @mbggenerated
     */
    private String memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invest_queue.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invest_queue.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invest_queue.amount
     *
     * @mbggenerated
     */
    private Long amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invest_queue.insert_time
     *
     * @mbggenerated
     */
    private Date insertTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invest_queue.queue_yyyymmdd
     *
     * @mbggenerated
     */
    private String queueYyyymmdd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invest_queue.order_time
     *
     * @mbggenerated
     */
    private Date orderTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invest_queue.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_invest_queue
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invest_queue.order_id
     *
     * @return the value of t_invest_queue.order_id
     *
     * @mbggenerated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invest_queue.order_id
     *
     * @param orderId the value for t_invest_queue.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invest_queue.orig_plan_main_id
     *
     * @return the value of t_invest_queue.orig_plan_main_id
     *
     * @mbggenerated
     */
    public String getOrigPlanMainId() {
        return origPlanMainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invest_queue.orig_plan_main_id
     *
     * @param origPlanMainId the value for t_invest_queue.orig_plan_main_id
     *
     * @mbggenerated
     */
    public void setOrigPlanMainId(String origPlanMainId) {
        this.origPlanMainId = origPlanMainId == null ? null : origPlanMainId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invest_queue.plan_id
     *
     * @return the value of t_invest_queue.plan_id
     *
     * @mbggenerated
     */
    public String getPlanId() {
        return planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invest_queue.plan_id
     *
     * @param planId the value for t_invest_queue.plan_id
     *
     * @mbggenerated
     */
    public void setPlanId(String planId) {
        this.planId = planId == null ? null : planId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invest_queue.member_id
     *
     * @return the value of t_invest_queue.member_id
     *
     * @mbggenerated
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invest_queue.member_id
     *
     * @param memberId the value for t_invest_queue.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId == null ? null : memberId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invest_queue.status
     *
     * @return the value of t_invest_queue.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invest_queue.status
     *
     * @param status the value for t_invest_queue.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invest_queue.type
     *
     * @return the value of t_invest_queue.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invest_queue.type
     *
     * @param type the value for t_invest_queue.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invest_queue.amount
     *
     * @return the value of t_invest_queue.amount
     *
     * @mbggenerated
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invest_queue.amount
     *
     * @param amount the value for t_invest_queue.amount
     *
     * @mbggenerated
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invest_queue.insert_time
     *
     * @return the value of t_invest_queue.insert_time
     *
     * @mbggenerated
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invest_queue.insert_time
     *
     * @param insertTime the value for t_invest_queue.insert_time
     *
     * @mbggenerated
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invest_queue.queue_yyyymmdd
     *
     * @return the value of t_invest_queue.queue_yyyymmdd
     *
     * @mbggenerated
     */
    public String getQueueYyyymmdd() {
        return queueYyyymmdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invest_queue.queue_yyyymmdd
     *
     * @param queueYyyymmdd the value for t_invest_queue.queue_yyyymmdd
     *
     * @mbggenerated
     */
    public void setQueueYyyymmdd(String queueYyyymmdd) {
        this.queueYyyymmdd = queueYyyymmdd == null ? null : queueYyyymmdd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invest_queue.order_time
     *
     * @return the value of t_invest_queue.order_time
     *
     * @mbggenerated
     */
    public Date getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invest_queue.order_time
     *
     * @param orderTime the value for t_invest_queue.order_time
     *
     * @mbggenerated
     */
    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invest_queue.remark
     *
     * @return the value of t_invest_queue.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invest_queue.remark
     *
     * @param remark the value for t_invest_queue.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}