package com.spring.fee.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TWheatFinancialExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_wheat_financial
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_wheat_financial
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_wheat_financial
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wheat_financial
     *
     * @mbggenerated
     */
    public TWheatFinancialExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wheat_financial
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wheat_financial
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wheat_financial
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wheat_financial
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wheat_financial
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wheat_financial
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wheat_financial
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wheat_financial
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wheat_financial
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wheat_financial
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_wheat_financial
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNull() {
            addCriterion("product_name is null");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNotNull() {
            addCriterion("product_name is not null");
            return (Criteria) this;
        }

        public Criteria andProductNameEqualTo(String value) {
            addCriterion("product_name =", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotEqualTo(String value) {
            addCriterion("product_name <>", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThan(String value) {
            addCriterion("product_name >", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThanOrEqualTo(String value) {
            addCriterion("product_name >=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThan(String value) {
            addCriterion("product_name <", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThanOrEqualTo(String value) {
            addCriterion("product_name <=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLike(String value) {
            addCriterion("product_name like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotLike(String value) {
            addCriterion("product_name not like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameIn(List<String> values) {
            addCriterion("product_name in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotIn(List<String> values) {
            addCriterion("product_name not in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameBetween(String value1, String value2) {
            addCriterion("product_name between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotBetween(String value1, String value2) {
            addCriterion("product_name not between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andYearProfitIsNull() {
            addCriterion("year_profit is null");
            return (Criteria) this;
        }

        public Criteria andYearProfitIsNotNull() {
            addCriterion("year_profit is not null");
            return (Criteria) this;
        }

        public Criteria andYearProfitEqualTo(Double value) {
            addCriterion("year_profit =", value, "yearProfit");
            return (Criteria) this;
        }

        public Criteria andYearProfitNotEqualTo(Double value) {
            addCriterion("year_profit <>", value, "yearProfit");
            return (Criteria) this;
        }

        public Criteria andYearProfitGreaterThan(Double value) {
            addCriterion("year_profit >", value, "yearProfit");
            return (Criteria) this;
        }

        public Criteria andYearProfitGreaterThanOrEqualTo(Double value) {
            addCriterion("year_profit >=", value, "yearProfit");
            return (Criteria) this;
        }

        public Criteria andYearProfitLessThan(Double value) {
            addCriterion("year_profit <", value, "yearProfit");
            return (Criteria) this;
        }

        public Criteria andYearProfitLessThanOrEqualTo(Double value) {
            addCriterion("year_profit <=", value, "yearProfit");
            return (Criteria) this;
        }

        public Criteria andYearProfitIn(List<Double> values) {
            addCriterion("year_profit in", values, "yearProfit");
            return (Criteria) this;
        }

        public Criteria andYearProfitNotIn(List<Double> values) {
            addCriterion("year_profit not in", values, "yearProfit");
            return (Criteria) this;
        }

        public Criteria andYearProfitBetween(Double value1, Double value2) {
            addCriterion("year_profit between", value1, value2, "yearProfit");
            return (Criteria) this;
        }

        public Criteria andYearProfitNotBetween(Double value1, Double value2) {
            addCriterion("year_profit not between", value1, value2, "yearProfit");
            return (Criteria) this;
        }

        public Criteria andMonthProfitIsNull() {
            addCriterion("month_profit is null");
            return (Criteria) this;
        }

        public Criteria andMonthProfitIsNotNull() {
            addCriterion("month_profit is not null");
            return (Criteria) this;
        }

        public Criteria andMonthProfitEqualTo(Double value) {
            addCriterion("month_profit =", value, "monthProfit");
            return (Criteria) this;
        }

        public Criteria andMonthProfitNotEqualTo(Double value) {
            addCriterion("month_profit <>", value, "monthProfit");
            return (Criteria) this;
        }

        public Criteria andMonthProfitGreaterThan(Double value) {
            addCriterion("month_profit >", value, "monthProfit");
            return (Criteria) this;
        }

        public Criteria andMonthProfitGreaterThanOrEqualTo(Double value) {
            addCriterion("month_profit >=", value, "monthProfit");
            return (Criteria) this;
        }

        public Criteria andMonthProfitLessThan(Double value) {
            addCriterion("month_profit <", value, "monthProfit");
            return (Criteria) this;
        }

        public Criteria andMonthProfitLessThanOrEqualTo(Double value) {
            addCriterion("month_profit <=", value, "monthProfit");
            return (Criteria) this;
        }

        public Criteria andMonthProfitIn(List<Double> values) {
            addCriterion("month_profit in", values, "monthProfit");
            return (Criteria) this;
        }

        public Criteria andMonthProfitNotIn(List<Double> values) {
            addCriterion("month_profit not in", values, "monthProfit");
            return (Criteria) this;
        }

        public Criteria andMonthProfitBetween(Double value1, Double value2) {
            addCriterion("month_profit between", value1, value2, "monthProfit");
            return (Criteria) this;
        }

        public Criteria andMonthProfitNotBetween(Double value1, Double value2) {
            addCriterion("month_profit not between", value1, value2, "monthProfit");
            return (Criteria) this;
        }

        public Criteria andBonusDayIsNull() {
            addCriterion("bonus_day is null");
            return (Criteria) this;
        }

        public Criteria andBonusDayIsNotNull() {
            addCriterion("bonus_day is not null");
            return (Criteria) this;
        }

        public Criteria andBonusDayEqualTo(Integer value) {
            addCriterion("bonus_day =", value, "bonusDay");
            return (Criteria) this;
        }

        public Criteria andBonusDayNotEqualTo(Integer value) {
            addCriterion("bonus_day <>", value, "bonusDay");
            return (Criteria) this;
        }

        public Criteria andBonusDayGreaterThan(Integer value) {
            addCriterion("bonus_day >", value, "bonusDay");
            return (Criteria) this;
        }

        public Criteria andBonusDayGreaterThanOrEqualTo(Integer value) {
            addCriterion("bonus_day >=", value, "bonusDay");
            return (Criteria) this;
        }

        public Criteria andBonusDayLessThan(Integer value) {
            addCriterion("bonus_day <", value, "bonusDay");
            return (Criteria) this;
        }

        public Criteria andBonusDayLessThanOrEqualTo(Integer value) {
            addCriterion("bonus_day <=", value, "bonusDay");
            return (Criteria) this;
        }

        public Criteria andBonusDayIn(List<Integer> values) {
            addCriterion("bonus_day in", values, "bonusDay");
            return (Criteria) this;
        }

        public Criteria andBonusDayNotIn(List<Integer> values) {
            addCriterion("bonus_day not in", values, "bonusDay");
            return (Criteria) this;
        }

        public Criteria andBonusDayBetween(Integer value1, Integer value2) {
            addCriterion("bonus_day between", value1, value2, "bonusDay");
            return (Criteria) this;
        }

        public Criteria andBonusDayNotBetween(Integer value1, Integer value2) {
            addCriterion("bonus_day not between", value1, value2, "bonusDay");
            return (Criteria) this;
        }

        public Criteria andDueTimeIsNull() {
            addCriterion("due_time is null");
            return (Criteria) this;
        }

        public Criteria andDueTimeIsNotNull() {
            addCriterion("due_time is not null");
            return (Criteria) this;
        }

        public Criteria andDueTimeEqualTo(Date value) {
            addCriterion("due_time =", value, "dueTime");
            return (Criteria) this;
        }

        public Criteria andDueTimeNotEqualTo(Date value) {
            addCriterion("due_time <>", value, "dueTime");
            return (Criteria) this;
        }

        public Criteria andDueTimeGreaterThan(Date value) {
            addCriterion("due_time >", value, "dueTime");
            return (Criteria) this;
        }

        public Criteria andDueTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("due_time >=", value, "dueTime");
            return (Criteria) this;
        }

        public Criteria andDueTimeLessThan(Date value) {
            addCriterion("due_time <", value, "dueTime");
            return (Criteria) this;
        }

        public Criteria andDueTimeLessThanOrEqualTo(Date value) {
            addCriterion("due_time <=", value, "dueTime");
            return (Criteria) this;
        }

        public Criteria andDueTimeIn(List<Date> values) {
            addCriterion("due_time in", values, "dueTime");
            return (Criteria) this;
        }

        public Criteria andDueTimeNotIn(List<Date> values) {
            addCriterion("due_time not in", values, "dueTime");
            return (Criteria) this;
        }

        public Criteria andDueTimeBetween(Date value1, Date value2) {
            addCriterion("due_time between", value1, value2, "dueTime");
            return (Criteria) this;
        }

        public Criteria andDueTimeNotBetween(Date value1, Date value2) {
            addCriterion("due_time not between", value1, value2, "dueTime");
            return (Criteria) this;
        }

        public Criteria andShelledNumberIsNull() {
            addCriterion("shelled_number is null");
            return (Criteria) this;
        }

        public Criteria andShelledNumberIsNotNull() {
            addCriterion("shelled_number is not null");
            return (Criteria) this;
        }

        public Criteria andShelledNumberEqualTo(Integer value) {
            addCriterion("shelled_number =", value, "shelledNumber");
            return (Criteria) this;
        }

        public Criteria andShelledNumberNotEqualTo(Integer value) {
            addCriterion("shelled_number <>", value, "shelledNumber");
            return (Criteria) this;
        }

        public Criteria andShelledNumberGreaterThan(Integer value) {
            addCriterion("shelled_number >", value, "shelledNumber");
            return (Criteria) this;
        }

        public Criteria andShelledNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("shelled_number >=", value, "shelledNumber");
            return (Criteria) this;
        }

        public Criteria andShelledNumberLessThan(Integer value) {
            addCriterion("shelled_number <", value, "shelledNumber");
            return (Criteria) this;
        }

        public Criteria andShelledNumberLessThanOrEqualTo(Integer value) {
            addCriterion("shelled_number <=", value, "shelledNumber");
            return (Criteria) this;
        }

        public Criteria andShelledNumberIn(List<Integer> values) {
            addCriterion("shelled_number in", values, "shelledNumber");
            return (Criteria) this;
        }

        public Criteria andShelledNumberNotIn(List<Integer> values) {
            addCriterion("shelled_number not in", values, "shelledNumber");
            return (Criteria) this;
        }

        public Criteria andShelledNumberBetween(Integer value1, Integer value2) {
            addCriterion("shelled_number between", value1, value2, "shelledNumber");
            return (Criteria) this;
        }

        public Criteria andShelledNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("shelled_number not between", value1, value2, "shelledNumber");
            return (Criteria) this;
        }

        public Criteria andAllNumberIsNull() {
            addCriterion("all_number is null");
            return (Criteria) this;
        }

        public Criteria andAllNumberIsNotNull() {
            addCriterion("all_number is not null");
            return (Criteria) this;
        }

        public Criteria andAllNumberEqualTo(Integer value) {
            addCriterion("all_number =", value, "allNumber");
            return (Criteria) this;
        }

        public Criteria andAllNumberNotEqualTo(Integer value) {
            addCriterion("all_number <>", value, "allNumber");
            return (Criteria) this;
        }

        public Criteria andAllNumberGreaterThan(Integer value) {
            addCriterion("all_number >", value, "allNumber");
            return (Criteria) this;
        }

        public Criteria andAllNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("all_number >=", value, "allNumber");
            return (Criteria) this;
        }

        public Criteria andAllNumberLessThan(Integer value) {
            addCriterion("all_number <", value, "allNumber");
            return (Criteria) this;
        }

        public Criteria andAllNumberLessThanOrEqualTo(Integer value) {
            addCriterion("all_number <=", value, "allNumber");
            return (Criteria) this;
        }

        public Criteria andAllNumberIn(List<Integer> values) {
            addCriterion("all_number in", values, "allNumber");
            return (Criteria) this;
        }

        public Criteria andAllNumberNotIn(List<Integer> values) {
            addCriterion("all_number not in", values, "allNumber");
            return (Criteria) this;
        }

        public Criteria andAllNumberBetween(Integer value1, Integer value2) {
            addCriterion("all_number between", value1, value2, "allNumber");
            return (Criteria) this;
        }

        public Criteria andAllNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("all_number not between", value1, value2, "allNumber");
            return (Criteria) this;
        }

        public Criteria andOncePriceIsNull() {
            addCriterion("once_price is null");
            return (Criteria) this;
        }

        public Criteria andOncePriceIsNotNull() {
            addCriterion("once_price is not null");
            return (Criteria) this;
        }

        public Criteria andOncePriceEqualTo(Long value) {
            addCriterion("once_price =", value, "oncePrice");
            return (Criteria) this;
        }

        public Criteria andOncePriceNotEqualTo(Long value) {
            addCriterion("once_price <>", value, "oncePrice");
            return (Criteria) this;
        }

        public Criteria andOncePriceGreaterThan(Long value) {
            addCriterion("once_price >", value, "oncePrice");
            return (Criteria) this;
        }

        public Criteria andOncePriceGreaterThanOrEqualTo(Long value) {
            addCriterion("once_price >=", value, "oncePrice");
            return (Criteria) this;
        }

        public Criteria andOncePriceLessThan(Long value) {
            addCriterion("once_price <", value, "oncePrice");
            return (Criteria) this;
        }

        public Criteria andOncePriceLessThanOrEqualTo(Long value) {
            addCriterion("once_price <=", value, "oncePrice");
            return (Criteria) this;
        }

        public Criteria andOncePriceIn(List<Long> values) {
            addCriterion("once_price in", values, "oncePrice");
            return (Criteria) this;
        }

        public Criteria andOncePriceNotIn(List<Long> values) {
            addCriterion("once_price not in", values, "oncePrice");
            return (Criteria) this;
        }

        public Criteria andOncePriceBetween(Long value1, Long value2) {
            addCriterion("once_price between", value1, value2, "oncePrice");
            return (Criteria) this;
        }

        public Criteria andOncePriceNotBetween(Long value1, Long value2) {
            addCriterion("once_price not between", value1, value2, "oncePrice");
            return (Criteria) this;
        }

        public Criteria andBuyruleIsNull() {
            addCriterion("buyrule is null");
            return (Criteria) this;
        }

        public Criteria andBuyruleIsNotNull() {
            addCriterion("buyrule is not null");
            return (Criteria) this;
        }

        public Criteria andBuyruleEqualTo(String value) {
            addCriterion("buyrule =", value, "buyrule");
            return (Criteria) this;
        }

        public Criteria andBuyruleNotEqualTo(String value) {
            addCriterion("buyrule <>", value, "buyrule");
            return (Criteria) this;
        }

        public Criteria andBuyruleGreaterThan(String value) {
            addCriterion("buyrule >", value, "buyrule");
            return (Criteria) this;
        }

        public Criteria andBuyruleGreaterThanOrEqualTo(String value) {
            addCriterion("buyrule >=", value, "buyrule");
            return (Criteria) this;
        }

        public Criteria andBuyruleLessThan(String value) {
            addCriterion("buyrule <", value, "buyrule");
            return (Criteria) this;
        }

        public Criteria andBuyruleLessThanOrEqualTo(String value) {
            addCriterion("buyrule <=", value, "buyrule");
            return (Criteria) this;
        }

        public Criteria andBuyruleLike(String value) {
            addCriterion("buyrule like", value, "buyrule");
            return (Criteria) this;
        }

        public Criteria andBuyruleNotLike(String value) {
            addCriterion("buyrule not like", value, "buyrule");
            return (Criteria) this;
        }

        public Criteria andBuyruleIn(List<String> values) {
            addCriterion("buyrule in", values, "buyrule");
            return (Criteria) this;
        }

        public Criteria andBuyruleNotIn(List<String> values) {
            addCriterion("buyrule not in", values, "buyrule");
            return (Criteria) this;
        }

        public Criteria andBuyruleBetween(String value1, String value2) {
            addCriterion("buyrule between", value1, value2, "buyrule");
            return (Criteria) this;
        }

        public Criteria andBuyruleNotBetween(String value1, String value2) {
            addCriterion("buyrule not between", value1, value2, "buyrule");
            return (Criteria) this;
        }

        public Criteria andImgIsNull() {
            addCriterion("img is null");
            return (Criteria) this;
        }

        public Criteria andImgIsNotNull() {
            addCriterion("img is not null");
            return (Criteria) this;
        }

        public Criteria andImgEqualTo(String value) {
            addCriterion("img =", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgNotEqualTo(String value) {
            addCriterion("img <>", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgGreaterThan(String value) {
            addCriterion("img >", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgGreaterThanOrEqualTo(String value) {
            addCriterion("img >=", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgLessThan(String value) {
            addCriterion("img <", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgLessThanOrEqualTo(String value) {
            addCriterion("img <=", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgLike(String value) {
            addCriterion("img like", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgNotLike(String value) {
            addCriterion("img not like", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgIn(List<String> values) {
            addCriterion("img in", values, "img");
            return (Criteria) this;
        }

        public Criteria andImgNotIn(List<String> values) {
            addCriterion("img not in", values, "img");
            return (Criteria) this;
        }

        public Criteria andImgBetween(String value1, String value2) {
            addCriterion("img between", value1, value2, "img");
            return (Criteria) this;
        }

        public Criteria andImgNotBetween(String value1, String value2) {
            addCriterion("img not between", value1, value2, "img");
            return (Criteria) this;
        }

        public Criteria andCycleIsNull() {
            addCriterion("cycle is null");
            return (Criteria) this;
        }

        public Criteria andCycleIsNotNull() {
            addCriterion("cycle is not null");
            return (Criteria) this;
        }

        public Criteria andCycleEqualTo(Integer value) {
            addCriterion("cycle =", value, "cycle");
            return (Criteria) this;
        }

        public Criteria andCycleNotEqualTo(Integer value) {
            addCriterion("cycle <>", value, "cycle");
            return (Criteria) this;
        }

        public Criteria andCycleGreaterThan(Integer value) {
            addCriterion("cycle >", value, "cycle");
            return (Criteria) this;
        }

        public Criteria andCycleGreaterThanOrEqualTo(Integer value) {
            addCriterion("cycle >=", value, "cycle");
            return (Criteria) this;
        }

        public Criteria andCycleLessThan(Integer value) {
            addCriterion("cycle <", value, "cycle");
            return (Criteria) this;
        }

        public Criteria andCycleLessThanOrEqualTo(Integer value) {
            addCriterion("cycle <=", value, "cycle");
            return (Criteria) this;
        }

        public Criteria andCycleIn(List<Integer> values) {
            addCriterion("cycle in", values, "cycle");
            return (Criteria) this;
        }

        public Criteria andCycleNotIn(List<Integer> values) {
            addCriterion("cycle not in", values, "cycle");
            return (Criteria) this;
        }

        public Criteria andCycleBetween(Integer value1, Integer value2) {
            addCriterion("cycle between", value1, value2, "cycle");
            return (Criteria) this;
        }

        public Criteria andCycleNotBetween(Integer value1, Integer value2) {
            addCriterion("cycle not between", value1, value2, "cycle");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(Integer value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(Integer value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(Integer value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(Integer value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(Integer value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<Integer> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<Integer> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(Integer value1, Integer value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(Integer value1, Integer value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("modify_time is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("modify_time is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(Date value) {
            addCriterion("modify_time =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(Date value) {
            addCriterion("modify_time <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(Date value) {
            addCriterion("modify_time >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("modify_time >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(Date value) {
            addCriterion("modify_time <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("modify_time <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<Date> values) {
            addCriterion("modify_time in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<Date> values) {
            addCriterion("modify_time not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(Date value1, Date value2) {
            addCriterion("modify_time between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("modify_time not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNull() {
            addCriterion("del_flag is null");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNotNull() {
            addCriterion("del_flag is not null");
            return (Criteria) this;
        }

        public Criteria andDelFlagEqualTo(Integer value) {
            addCriterion("del_flag =", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotEqualTo(Integer value) {
            addCriterion("del_flag <>", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThan(Integer value) {
            addCriterion("del_flag >", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("del_flag >=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThan(Integer value) {
            addCriterion("del_flag <", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThanOrEqualTo(Integer value) {
            addCriterion("del_flag <=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagIn(List<Integer> values) {
            addCriterion("del_flag in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotIn(List<Integer> values) {
            addCriterion("del_flag not in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagBetween(Integer value1, Integer value2) {
            addCriterion("del_flag between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("del_flag not between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Long value) {
            addCriterion("version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Long value) {
            addCriterion("version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Long value) {
            addCriterion("version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Long value) {
            addCriterion("version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Long value) {
            addCriterion("version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Long value) {
            addCriterion("version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Long> values) {
            addCriterion("version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Long> values) {
            addCriterion("version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Long value1, Long value2) {
            addCriterion("version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Long value1, Long value2) {
            addCriterion("version not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andExpand1IsNull() {
            addCriterion("expand_1 is null");
            return (Criteria) this;
        }

        public Criteria andExpand1IsNotNull() {
            addCriterion("expand_1 is not null");
            return (Criteria) this;
        }

        public Criteria andExpand1EqualTo(String value) {
            addCriterion("expand_1 =", value, "expand1");
            return (Criteria) this;
        }

        public Criteria andExpand1NotEqualTo(String value) {
            addCriterion("expand_1 <>", value, "expand1");
            return (Criteria) this;
        }

        public Criteria andExpand1GreaterThan(String value) {
            addCriterion("expand_1 >", value, "expand1");
            return (Criteria) this;
        }

        public Criteria andExpand1GreaterThanOrEqualTo(String value) {
            addCriterion("expand_1 >=", value, "expand1");
            return (Criteria) this;
        }

        public Criteria andExpand1LessThan(String value) {
            addCriterion("expand_1 <", value, "expand1");
            return (Criteria) this;
        }

        public Criteria andExpand1LessThanOrEqualTo(String value) {
            addCriterion("expand_1 <=", value, "expand1");
            return (Criteria) this;
        }

        public Criteria andExpand1Like(String value) {
            addCriterion("expand_1 like", value, "expand1");
            return (Criteria) this;
        }

        public Criteria andExpand1NotLike(String value) {
            addCriterion("expand_1 not like", value, "expand1");
            return (Criteria) this;
        }

        public Criteria andExpand1In(List<String> values) {
            addCriterion("expand_1 in", values, "expand1");
            return (Criteria) this;
        }

        public Criteria andExpand1NotIn(List<String> values) {
            addCriterion("expand_1 not in", values, "expand1");
            return (Criteria) this;
        }

        public Criteria andExpand1Between(String value1, String value2) {
            addCriterion("expand_1 between", value1, value2, "expand1");
            return (Criteria) this;
        }

        public Criteria andExpand1NotBetween(String value1, String value2) {
            addCriterion("expand_1 not between", value1, value2, "expand1");
            return (Criteria) this;
        }

        public Criteria andExpand2IsNull() {
            addCriterion("expand_2 is null");
            return (Criteria) this;
        }

        public Criteria andExpand2IsNotNull() {
            addCriterion("expand_2 is not null");
            return (Criteria) this;
        }

        public Criteria andExpand2EqualTo(String value) {
            addCriterion("expand_2 =", value, "expand2");
            return (Criteria) this;
        }

        public Criteria andExpand2NotEqualTo(String value) {
            addCriterion("expand_2 <>", value, "expand2");
            return (Criteria) this;
        }

        public Criteria andExpand2GreaterThan(String value) {
            addCriterion("expand_2 >", value, "expand2");
            return (Criteria) this;
        }

        public Criteria andExpand2GreaterThanOrEqualTo(String value) {
            addCriterion("expand_2 >=", value, "expand2");
            return (Criteria) this;
        }

        public Criteria andExpand2LessThan(String value) {
            addCriterion("expand_2 <", value, "expand2");
            return (Criteria) this;
        }

        public Criteria andExpand2LessThanOrEqualTo(String value) {
            addCriterion("expand_2 <=", value, "expand2");
            return (Criteria) this;
        }

        public Criteria andExpand2Like(String value) {
            addCriterion("expand_2 like", value, "expand2");
            return (Criteria) this;
        }

        public Criteria andExpand2NotLike(String value) {
            addCriterion("expand_2 not like", value, "expand2");
            return (Criteria) this;
        }

        public Criteria andExpand2In(List<String> values) {
            addCriterion("expand_2 in", values, "expand2");
            return (Criteria) this;
        }

        public Criteria andExpand2NotIn(List<String> values) {
            addCriterion("expand_2 not in", values, "expand2");
            return (Criteria) this;
        }

        public Criteria andExpand2Between(String value1, String value2) {
            addCriterion("expand_2 between", value1, value2, "expand2");
            return (Criteria) this;
        }

        public Criteria andExpand2NotBetween(String value1, String value2) {
            addCriterion("expand_2 not between", value1, value2, "expand2");
            return (Criteria) this;
        }

        public Criteria andExpand3IsNull() {
            addCriterion("expand_3 is null");
            return (Criteria) this;
        }

        public Criteria andExpand3IsNotNull() {
            addCriterion("expand_3 is not null");
            return (Criteria) this;
        }

        public Criteria andExpand3EqualTo(String value) {
            addCriterion("expand_3 =", value, "expand3");
            return (Criteria) this;
        }

        public Criteria andExpand3NotEqualTo(String value) {
            addCriterion("expand_3 <>", value, "expand3");
            return (Criteria) this;
        }

        public Criteria andExpand3GreaterThan(String value) {
            addCriterion("expand_3 >", value, "expand3");
            return (Criteria) this;
        }

        public Criteria andExpand3GreaterThanOrEqualTo(String value) {
            addCriterion("expand_3 >=", value, "expand3");
            return (Criteria) this;
        }

        public Criteria andExpand3LessThan(String value) {
            addCriterion("expand_3 <", value, "expand3");
            return (Criteria) this;
        }

        public Criteria andExpand3LessThanOrEqualTo(String value) {
            addCriterion("expand_3 <=", value, "expand3");
            return (Criteria) this;
        }

        public Criteria andExpand3Like(String value) {
            addCriterion("expand_3 like", value, "expand3");
            return (Criteria) this;
        }

        public Criteria andExpand3NotLike(String value) {
            addCriterion("expand_3 not like", value, "expand3");
            return (Criteria) this;
        }

        public Criteria andExpand3In(List<String> values) {
            addCriterion("expand_3 in", values, "expand3");
            return (Criteria) this;
        }

        public Criteria andExpand3NotIn(List<String> values) {
            addCriterion("expand_3 not in", values, "expand3");
            return (Criteria) this;
        }

        public Criteria andExpand3Between(String value1, String value2) {
            addCriterion("expand_3 between", value1, value2, "expand3");
            return (Criteria) this;
        }

        public Criteria andExpand3NotBetween(String value1, String value2) {
            addCriterion("expand_3 not between", value1, value2, "expand3");
            return (Criteria) this;
        }

        public Criteria andExpand4IsNull() {
            addCriterion("expand_4 is null");
            return (Criteria) this;
        }

        public Criteria andExpand4IsNotNull() {
            addCriterion("expand_4 is not null");
            return (Criteria) this;
        }

        public Criteria andExpand4EqualTo(String value) {
            addCriterion("expand_4 =", value, "expand4");
            return (Criteria) this;
        }

        public Criteria andExpand4NotEqualTo(String value) {
            addCriterion("expand_4 <>", value, "expand4");
            return (Criteria) this;
        }

        public Criteria andExpand4GreaterThan(String value) {
            addCriterion("expand_4 >", value, "expand4");
            return (Criteria) this;
        }

        public Criteria andExpand4GreaterThanOrEqualTo(String value) {
            addCriterion("expand_4 >=", value, "expand4");
            return (Criteria) this;
        }

        public Criteria andExpand4LessThan(String value) {
            addCriterion("expand_4 <", value, "expand4");
            return (Criteria) this;
        }

        public Criteria andExpand4LessThanOrEqualTo(String value) {
            addCriterion("expand_4 <=", value, "expand4");
            return (Criteria) this;
        }

        public Criteria andExpand4Like(String value) {
            addCriterion("expand_4 like", value, "expand4");
            return (Criteria) this;
        }

        public Criteria andExpand4NotLike(String value) {
            addCriterion("expand_4 not like", value, "expand4");
            return (Criteria) this;
        }

        public Criteria andExpand4In(List<String> values) {
            addCriterion("expand_4 in", values, "expand4");
            return (Criteria) this;
        }

        public Criteria andExpand4NotIn(List<String> values) {
            addCriterion("expand_4 not in", values, "expand4");
            return (Criteria) this;
        }

        public Criteria andExpand4Between(String value1, String value2) {
            addCriterion("expand_4 between", value1, value2, "expand4");
            return (Criteria) this;
        }

        public Criteria andExpand4NotBetween(String value1, String value2) {
            addCriterion("expand_4 not between", value1, value2, "expand4");
            return (Criteria) this;
        }

        public Criteria andExpand5IsNull() {
            addCriterion("expand_5 is null");
            return (Criteria) this;
        }

        public Criteria andExpand5IsNotNull() {
            addCriterion("expand_5 is not null");
            return (Criteria) this;
        }

        public Criteria andExpand5EqualTo(String value) {
            addCriterion("expand_5 =", value, "expand5");
            return (Criteria) this;
        }

        public Criteria andExpand5NotEqualTo(String value) {
            addCriterion("expand_5 <>", value, "expand5");
            return (Criteria) this;
        }

        public Criteria andExpand5GreaterThan(String value) {
            addCriterion("expand_5 >", value, "expand5");
            return (Criteria) this;
        }

        public Criteria andExpand5GreaterThanOrEqualTo(String value) {
            addCriterion("expand_5 >=", value, "expand5");
            return (Criteria) this;
        }

        public Criteria andExpand5LessThan(String value) {
            addCriterion("expand_5 <", value, "expand5");
            return (Criteria) this;
        }

        public Criteria andExpand5LessThanOrEqualTo(String value) {
            addCriterion("expand_5 <=", value, "expand5");
            return (Criteria) this;
        }

        public Criteria andExpand5Like(String value) {
            addCriterion("expand_5 like", value, "expand5");
            return (Criteria) this;
        }

        public Criteria andExpand5NotLike(String value) {
            addCriterion("expand_5 not like", value, "expand5");
            return (Criteria) this;
        }

        public Criteria andExpand5In(List<String> values) {
            addCriterion("expand_5 in", values, "expand5");
            return (Criteria) this;
        }

        public Criteria andExpand5NotIn(List<String> values) {
            addCriterion("expand_5 not in", values, "expand5");
            return (Criteria) this;
        }

        public Criteria andExpand5Between(String value1, String value2) {
            addCriterion("expand_5 between", value1, value2, "expand5");
            return (Criteria) this;
        }

        public Criteria andExpand5NotBetween(String value1, String value2) {
            addCriterion("expand_5 not between", value1, value2, "expand5");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_wheat_financial
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_wheat_financial
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}