package com.spring.fee.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class TWheatFinancialOrderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_wheat_financial_order
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_wheat_financial_order
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_wheat_financial_order
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wheat_financial_order
     *
     * @mbggenerated
     */
    public TWheatFinancialOrderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wheat_financial_order
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wheat_financial_order
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wheat_financial_order
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wheat_financial_order
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wheat_financial_order
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wheat_financial_order
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wheat_financial_order
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wheat_financial_order
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wheat_financial_order
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wheat_financial_order
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_wheat_financial_order
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andMemIdIsNull() {
            addCriterion("mem_id is null");
            return (Criteria) this;
        }

        public Criteria andMemIdIsNotNull() {
            addCriterion("mem_id is not null");
            return (Criteria) this;
        }

        public Criteria andMemIdEqualTo(Long value) {
            addCriterion("mem_id =", value, "memId");
            return (Criteria) this;
        }

        public Criteria andMemIdNotEqualTo(Long value) {
            addCriterion("mem_id <>", value, "memId");
            return (Criteria) this;
        }

        public Criteria andMemIdGreaterThan(Long value) {
            addCriterion("mem_id >", value, "memId");
            return (Criteria) this;
        }

        public Criteria andMemIdGreaterThanOrEqualTo(Long value) {
            addCriterion("mem_id >=", value, "memId");
            return (Criteria) this;
        }

        public Criteria andMemIdLessThan(Long value) {
            addCriterion("mem_id <", value, "memId");
            return (Criteria) this;
        }

        public Criteria andMemIdLessThanOrEqualTo(Long value) {
            addCriterion("mem_id <=", value, "memId");
            return (Criteria) this;
        }

        public Criteria andMemIdIn(List<Long> values) {
            addCriterion("mem_id in", values, "memId");
            return (Criteria) this;
        }

        public Criteria andMemIdNotIn(List<Long> values) {
            addCriterion("mem_id not in", values, "memId");
            return (Criteria) this;
        }

        public Criteria andMemIdBetween(Long value1, Long value2) {
            addCriterion("mem_id between", value1, value2, "memId");
            return (Criteria) this;
        }

        public Criteria andMemIdNotBetween(Long value1, Long value2) {
            addCriterion("mem_id not between", value1, value2, "memId");
            return (Criteria) this;
        }

        public Criteria andMemberIdIsNull() {
            addCriterion("member_id is null");
            return (Criteria) this;
        }

        public Criteria andMemberIdIsNotNull() {
            addCriterion("member_id is not null");
            return (Criteria) this;
        }

        public Criteria andMemberIdEqualTo(String value) {
            addCriterion("member_id =", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdNotEqualTo(String value) {
            addCriterion("member_id <>", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdGreaterThan(String value) {
            addCriterion("member_id >", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdGreaterThanOrEqualTo(String value) {
            addCriterion("member_id >=", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdLessThan(String value) {
            addCriterion("member_id <", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdLessThanOrEqualTo(String value) {
            addCriterion("member_id <=", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdLike(String value) {
            addCriterion("member_id like", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdNotLike(String value) {
            addCriterion("member_id not like", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdIn(List<String> values) {
            addCriterion("member_id in", values, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdNotIn(List<String> values) {
            addCriterion("member_id not in", values, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdBetween(String value1, String value2) {
            addCriterion("member_id between", value1, value2, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdNotBetween(String value1, String value2) {
            addCriterion("member_id not between", value1, value2, "memberId");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNull() {
            addCriterion("phone is null");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNotNull() {
            addCriterion("phone is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneEqualTo(String value) {
            addCriterion("phone =", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotEqualTo(String value) {
            addCriterion("phone <>", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThan(String value) {
            addCriterion("phone >", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("phone >=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThan(String value) {
            addCriterion("phone <", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThanOrEqualTo(String value) {
            addCriterion("phone <=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLike(String value) {
            addCriterion("phone like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotLike(String value) {
            addCriterion("phone not like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneIn(List<String> values) {
            addCriterion("phone in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotIn(List<String> values) {
            addCriterion("phone not in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneBetween(String value1, String value2) {
            addCriterion("phone between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotBetween(String value1, String value2) {
            addCriterion("phone not between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andOrderCodeIsNull() {
            addCriterion("order_code is null");
            return (Criteria) this;
        }

        public Criteria andOrderCodeIsNotNull() {
            addCriterion("order_code is not null");
            return (Criteria) this;
        }

        public Criteria andOrderCodeEqualTo(String value) {
            addCriterion("order_code =", value, "orderCode");
            return (Criteria) this;
        }

        public Criteria andOrderCodeNotEqualTo(String value) {
            addCriterion("order_code <>", value, "orderCode");
            return (Criteria) this;
        }

        public Criteria andOrderCodeGreaterThan(String value) {
            addCriterion("order_code >", value, "orderCode");
            return (Criteria) this;
        }

        public Criteria andOrderCodeGreaterThanOrEqualTo(String value) {
            addCriterion("order_code >=", value, "orderCode");
            return (Criteria) this;
        }

        public Criteria andOrderCodeLessThan(String value) {
            addCriterion("order_code <", value, "orderCode");
            return (Criteria) this;
        }

        public Criteria andOrderCodeLessThanOrEqualTo(String value) {
            addCriterion("order_code <=", value, "orderCode");
            return (Criteria) this;
        }

        public Criteria andOrderCodeLike(String value) {
            addCriterion("order_code like", value, "orderCode");
            return (Criteria) this;
        }

        public Criteria andOrderCodeNotLike(String value) {
            addCriterion("order_code not like", value, "orderCode");
            return (Criteria) this;
        }

        public Criteria andOrderCodeIn(List<String> values) {
            addCriterion("order_code in", values, "orderCode");
            return (Criteria) this;
        }

        public Criteria andOrderCodeNotIn(List<String> values) {
            addCriterion("order_code not in", values, "orderCode");
            return (Criteria) this;
        }

        public Criteria andOrderCodeBetween(String value1, String value2) {
            addCriterion("order_code between", value1, value2, "orderCode");
            return (Criteria) this;
        }

        public Criteria andOrderCodeNotBetween(String value1, String value2) {
            addCriterion("order_code not between", value1, value2, "orderCode");
            return (Criteria) this;
        }

        public Criteria andFinancialIdIsNull() {
            addCriterion("financial_id is null");
            return (Criteria) this;
        }

        public Criteria andFinancialIdIsNotNull() {
            addCriterion("financial_id is not null");
            return (Criteria) this;
        }

        public Criteria andFinancialIdEqualTo(Long value) {
            addCriterion("financial_id =", value, "financialId");
            return (Criteria) this;
        }

        public Criteria andFinancialIdNotEqualTo(Long value) {
            addCriterion("financial_id <>", value, "financialId");
            return (Criteria) this;
        }

        public Criteria andFinancialIdGreaterThan(Long value) {
            addCriterion("financial_id >", value, "financialId");
            return (Criteria) this;
        }

        public Criteria andFinancialIdGreaterThanOrEqualTo(Long value) {
            addCriterion("financial_id >=", value, "financialId");
            return (Criteria) this;
        }

        public Criteria andFinancialIdLessThan(Long value) {
            addCriterion("financial_id <", value, "financialId");
            return (Criteria) this;
        }

        public Criteria andFinancialIdLessThanOrEqualTo(Long value) {
            addCriterion("financial_id <=", value, "financialId");
            return (Criteria) this;
        }

        public Criteria andFinancialIdIn(List<Long> values) {
            addCriterion("financial_id in", values, "financialId");
            return (Criteria) this;
        }

        public Criteria andFinancialIdNotIn(List<Long> values) {
            addCriterion("financial_id not in", values, "financialId");
            return (Criteria) this;
        }

        public Criteria andFinancialIdBetween(Long value1, Long value2) {
            addCriterion("financial_id between", value1, value2, "financialId");
            return (Criteria) this;
        }

        public Criteria andFinancialIdNotBetween(Long value1, Long value2) {
            addCriterion("financial_id not between", value1, value2, "financialId");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNull() {
            addCriterion("product_name is null");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNotNull() {
            addCriterion("product_name is not null");
            return (Criteria) this;
        }

        public Criteria andProductNameEqualTo(String value) {
            addCriterion("product_name =", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotEqualTo(String value) {
            addCriterion("product_name <>", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThan(String value) {
            addCriterion("product_name >", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThanOrEqualTo(String value) {
            addCriterion("product_name >=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThan(String value) {
            addCriterion("product_name <", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThanOrEqualTo(String value) {
            addCriterion("product_name <=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLike(String value) {
            addCriterion("product_name like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotLike(String value) {
            addCriterion("product_name not like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameIn(List<String> values) {
            addCriterion("product_name in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotIn(List<String> values) {
            addCriterion("product_name not in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameBetween(String value1, String value2) {
            addCriterion("product_name between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotBetween(String value1, String value2) {
            addCriterion("product_name not between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andCycleIsNull() {
            addCriterion("cycle is null");
            return (Criteria) this;
        }

        public Criteria andCycleIsNotNull() {
            addCriterion("cycle is not null");
            return (Criteria) this;
        }

        public Criteria andCycleEqualTo(Integer value) {
            addCriterion("cycle =", value, "cycle");
            return (Criteria) this;
        }

        public Criteria andCycleNotEqualTo(Integer value) {
            addCriterion("cycle <>", value, "cycle");
            return (Criteria) this;
        }

        public Criteria andCycleGreaterThan(Integer value) {
            addCriterion("cycle >", value, "cycle");
            return (Criteria) this;
        }

        public Criteria andCycleGreaterThanOrEqualTo(Integer value) {
            addCriterion("cycle >=", value, "cycle");
            return (Criteria) this;
        }

        public Criteria andCycleLessThan(Integer value) {
            addCriterion("cycle <", value, "cycle");
            return (Criteria) this;
        }

        public Criteria andCycleLessThanOrEqualTo(Integer value) {
            addCriterion("cycle <=", value, "cycle");
            return (Criteria) this;
        }

        public Criteria andCycleIn(List<Integer> values) {
            addCriterion("cycle in", values, "cycle");
            return (Criteria) this;
        }

        public Criteria andCycleNotIn(List<Integer> values) {
            addCriterion("cycle not in", values, "cycle");
            return (Criteria) this;
        }

        public Criteria andCycleBetween(Integer value1, Integer value2) {
            addCriterion("cycle between", value1, value2, "cycle");
            return (Criteria) this;
        }

        public Criteria andCycleNotBetween(Integer value1, Integer value2) {
            addCriterion("cycle not between", value1, value2, "cycle");
            return (Criteria) this;
        }

        public Criteria andYearProfitIsNull() {
            addCriterion("year_profit is null");
            return (Criteria) this;
        }

        public Criteria andYearProfitIsNotNull() {
            addCriterion("year_profit is not null");
            return (Criteria) this;
        }

        public Criteria andYearProfitEqualTo(Double value) {
            addCriterion("year_profit =", value, "yearProfit");
            return (Criteria) this;
        }

        public Criteria andYearProfitNotEqualTo(Double value) {
            addCriterion("year_profit <>", value, "yearProfit");
            return (Criteria) this;
        }

        public Criteria andYearProfitGreaterThan(Double value) {
            addCriterion("year_profit >", value, "yearProfit");
            return (Criteria) this;
        }

        public Criteria andYearProfitGreaterThanOrEqualTo(Double value) {
            addCriterion("year_profit >=", value, "yearProfit");
            return (Criteria) this;
        }

        public Criteria andYearProfitLessThan(Double value) {
            addCriterion("year_profit <", value, "yearProfit");
            return (Criteria) this;
        }

        public Criteria andYearProfitLessThanOrEqualTo(Double value) {
            addCriterion("year_profit <=", value, "yearProfit");
            return (Criteria) this;
        }

        public Criteria andYearProfitIn(List<Double> values) {
            addCriterion("year_profit in", values, "yearProfit");
            return (Criteria) this;
        }

        public Criteria andYearProfitNotIn(List<Double> values) {
            addCriterion("year_profit not in", values, "yearProfit");
            return (Criteria) this;
        }

        public Criteria andYearProfitBetween(Double value1, Double value2) {
            addCriterion("year_profit between", value1, value2, "yearProfit");
            return (Criteria) this;
        }

        public Criteria andYearProfitNotBetween(Double value1, Double value2) {
            addCriterion("year_profit not between", value1, value2, "yearProfit");
            return (Criteria) this;
        }

        public Criteria andMonthProfitIsNull() {
            addCriterion("month_profit is null");
            return (Criteria) this;
        }

        public Criteria andMonthProfitIsNotNull() {
            addCriterion("month_profit is not null");
            return (Criteria) this;
        }

        public Criteria andMonthProfitEqualTo(Double value) {
            addCriterion("month_profit =", value, "monthProfit");
            return (Criteria) this;
        }

        public Criteria andMonthProfitNotEqualTo(Double value) {
            addCriterion("month_profit <>", value, "monthProfit");
            return (Criteria) this;
        }

        public Criteria andMonthProfitGreaterThan(Double value) {
            addCriterion("month_profit >", value, "monthProfit");
            return (Criteria) this;
        }

        public Criteria andMonthProfitGreaterThanOrEqualTo(Double value) {
            addCriterion("month_profit >=", value, "monthProfit");
            return (Criteria) this;
        }

        public Criteria andMonthProfitLessThan(Double value) {
            addCriterion("month_profit <", value, "monthProfit");
            return (Criteria) this;
        }

        public Criteria andMonthProfitLessThanOrEqualTo(Double value) {
            addCriterion("month_profit <=", value, "monthProfit");
            return (Criteria) this;
        }

        public Criteria andMonthProfitIn(List<Double> values) {
            addCriterion("month_profit in", values, "monthProfit");
            return (Criteria) this;
        }

        public Criteria andMonthProfitNotIn(List<Double> values) {
            addCriterion("month_profit not in", values, "monthProfit");
            return (Criteria) this;
        }

        public Criteria andMonthProfitBetween(Double value1, Double value2) {
            addCriterion("month_profit between", value1, value2, "monthProfit");
            return (Criteria) this;
        }

        public Criteria andMonthProfitNotBetween(Double value1, Double value2) {
            addCriterion("month_profit not between", value1, value2, "monthProfit");
            return (Criteria) this;
        }

        public Criteria andBonusDayIsNull() {
            addCriterion("bonus_day is null");
            return (Criteria) this;
        }

        public Criteria andBonusDayIsNotNull() {
            addCriterion("bonus_day is not null");
            return (Criteria) this;
        }

        public Criteria andBonusDayEqualTo(Date value) {
            addCriterionForJDBCDate("bonus_day =", value, "bonusDay");
            return (Criteria) this;
        }

        public Criteria andBonusDayNotEqualTo(Date value) {
            addCriterionForJDBCDate("bonus_day <>", value, "bonusDay");
            return (Criteria) this;
        }

        public Criteria andBonusDayGreaterThan(Date value) {
            addCriterionForJDBCDate("bonus_day >", value, "bonusDay");
            return (Criteria) this;
        }

        public Criteria andBonusDayGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("bonus_day >=", value, "bonusDay");
            return (Criteria) this;
        }

        public Criteria andBonusDayLessThan(Date value) {
            addCriterionForJDBCDate("bonus_day <", value, "bonusDay");
            return (Criteria) this;
        }

        public Criteria andBonusDayLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("bonus_day <=", value, "bonusDay");
            return (Criteria) this;
        }

        public Criteria andBonusDayIn(List<Date> values) {
            addCriterionForJDBCDate("bonus_day in", values, "bonusDay");
            return (Criteria) this;
        }

        public Criteria andBonusDayNotIn(List<Date> values) {
            addCriterionForJDBCDate("bonus_day not in", values, "bonusDay");
            return (Criteria) this;
        }

        public Criteria andBonusDayBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("bonus_day between", value1, value2, "bonusDay");
            return (Criteria) this;
        }

        public Criteria andBonusDayNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("bonus_day not between", value1, value2, "bonusDay");
            return (Criteria) this;
        }

        public Criteria andDueTimeIsNull() {
            addCriterion("due_time is null");
            return (Criteria) this;
        }

        public Criteria andDueTimeIsNotNull() {
            addCriterion("due_time is not null");
            return (Criteria) this;
        }

        public Criteria andDueTimeEqualTo(Date value) {
            addCriterion("due_time =", value, "dueTime");
            return (Criteria) this;
        }

        public Criteria andDueTimeNotEqualTo(Date value) {
            addCriterion("due_time <>", value, "dueTime");
            return (Criteria) this;
        }

        public Criteria andDueTimeGreaterThan(Date value) {
            addCriterion("due_time >", value, "dueTime");
            return (Criteria) this;
        }

        public Criteria andDueTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("due_time >=", value, "dueTime");
            return (Criteria) this;
        }

        public Criteria andDueTimeLessThan(Date value) {
            addCriterion("due_time <", value, "dueTime");
            return (Criteria) this;
        }

        public Criteria andDueTimeLessThanOrEqualTo(Date value) {
            addCriterion("due_time <=", value, "dueTime");
            return (Criteria) this;
        }

        public Criteria andDueTimeIn(List<Date> values) {
            addCriterion("due_time in", values, "dueTime");
            return (Criteria) this;
        }

        public Criteria andDueTimeNotIn(List<Date> values) {
            addCriterion("due_time not in", values, "dueTime");
            return (Criteria) this;
        }

        public Criteria andDueTimeBetween(Date value1, Date value2) {
            addCriterion("due_time between", value1, value2, "dueTime");
            return (Criteria) this;
        }

        public Criteria andDueTimeNotBetween(Date value1, Date value2) {
            addCriterion("due_time not between", value1, value2, "dueTime");
            return (Criteria) this;
        }

        public Criteria andBuyNumberIsNull() {
            addCriterion("buy_number is null");
            return (Criteria) this;
        }

        public Criteria andBuyNumberIsNotNull() {
            addCriterion("buy_number is not null");
            return (Criteria) this;
        }

        public Criteria andBuyNumberEqualTo(Integer value) {
            addCriterion("buy_number =", value, "buyNumber");
            return (Criteria) this;
        }

        public Criteria andBuyNumberNotEqualTo(Integer value) {
            addCriterion("buy_number <>", value, "buyNumber");
            return (Criteria) this;
        }

        public Criteria andBuyNumberGreaterThan(Integer value) {
            addCriterion("buy_number >", value, "buyNumber");
            return (Criteria) this;
        }

        public Criteria andBuyNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("buy_number >=", value, "buyNumber");
            return (Criteria) this;
        }

        public Criteria andBuyNumberLessThan(Integer value) {
            addCriterion("buy_number <", value, "buyNumber");
            return (Criteria) this;
        }

        public Criteria andBuyNumberLessThanOrEqualTo(Integer value) {
            addCriterion("buy_number <=", value, "buyNumber");
            return (Criteria) this;
        }

        public Criteria andBuyNumberIn(List<Integer> values) {
            addCriterion("buy_number in", values, "buyNumber");
            return (Criteria) this;
        }

        public Criteria andBuyNumberNotIn(List<Integer> values) {
            addCriterion("buy_number not in", values, "buyNumber");
            return (Criteria) this;
        }

        public Criteria andBuyNumberBetween(Integer value1, Integer value2) {
            addCriterion("buy_number between", value1, value2, "buyNumber");
            return (Criteria) this;
        }

        public Criteria andBuyNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("buy_number not between", value1, value2, "buyNumber");
            return (Criteria) this;
        }

        public Criteria andOncePriceIsNull() {
            addCriterion("once_price is null");
            return (Criteria) this;
        }

        public Criteria andOncePriceIsNotNull() {
            addCriterion("once_price is not null");
            return (Criteria) this;
        }

        public Criteria andOncePriceEqualTo(Long value) {
            addCriterion("once_price =", value, "oncePrice");
            return (Criteria) this;
        }

        public Criteria andOncePriceNotEqualTo(Long value) {
            addCriterion("once_price <>", value, "oncePrice");
            return (Criteria) this;
        }

        public Criteria andOncePriceGreaterThan(Long value) {
            addCriterion("once_price >", value, "oncePrice");
            return (Criteria) this;
        }

        public Criteria andOncePriceGreaterThanOrEqualTo(Long value) {
            addCriterion("once_price >=", value, "oncePrice");
            return (Criteria) this;
        }

        public Criteria andOncePriceLessThan(Long value) {
            addCriterion("once_price <", value, "oncePrice");
            return (Criteria) this;
        }

        public Criteria andOncePriceLessThanOrEqualTo(Long value) {
            addCriterion("once_price <=", value, "oncePrice");
            return (Criteria) this;
        }

        public Criteria andOncePriceIn(List<Long> values) {
            addCriterion("once_price in", values, "oncePrice");
            return (Criteria) this;
        }

        public Criteria andOncePriceNotIn(List<Long> values) {
            addCriterion("once_price not in", values, "oncePrice");
            return (Criteria) this;
        }

        public Criteria andOncePriceBetween(Long value1, Long value2) {
            addCriterion("once_price between", value1, value2, "oncePrice");
            return (Criteria) this;
        }

        public Criteria andOncePriceNotBetween(Long value1, Long value2) {
            addCriterion("once_price not between", value1, value2, "oncePrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceIsNull() {
            addCriterion("total_price is null");
            return (Criteria) this;
        }

        public Criteria andTotalPriceIsNotNull() {
            addCriterion("total_price is not null");
            return (Criteria) this;
        }

        public Criteria andTotalPriceEqualTo(Long value) {
            addCriterion("total_price =", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceNotEqualTo(Long value) {
            addCriterion("total_price <>", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceGreaterThan(Long value) {
            addCriterion("total_price >", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceGreaterThanOrEqualTo(Long value) {
            addCriterion("total_price >=", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceLessThan(Long value) {
            addCriterion("total_price <", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceLessThanOrEqualTo(Long value) {
            addCriterion("total_price <=", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceIn(List<Long> values) {
            addCriterion("total_price in", values, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceNotIn(List<Long> values) {
            addCriterion("total_price not in", values, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceBetween(Long value1, Long value2) {
            addCriterion("total_price between", value1, value2, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceNotBetween(Long value1, Long value2) {
            addCriterion("total_price not between", value1, value2, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andInterestIsNull() {
            addCriterion("interest is null");
            return (Criteria) this;
        }

        public Criteria andInterestIsNotNull() {
            addCriterion("interest is not null");
            return (Criteria) this;
        }

        public Criteria andInterestEqualTo(Long value) {
            addCriterion("interest =", value, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestNotEqualTo(Long value) {
            addCriterion("interest <>", value, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestGreaterThan(Long value) {
            addCriterion("interest >", value, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestGreaterThanOrEqualTo(Long value) {
            addCriterion("interest >=", value, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestLessThan(Long value) {
            addCriterion("interest <", value, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestLessThanOrEqualTo(Long value) {
            addCriterion("interest <=", value, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestIn(List<Long> values) {
            addCriterion("interest in", values, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestNotIn(List<Long> values) {
            addCriterion("interest not in", values, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestBetween(Long value1, Long value2) {
            addCriterion("interest between", value1, value2, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestNotBetween(Long value1, Long value2) {
            addCriterion("interest not between", value1, value2, "interest");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("modify_time is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("modify_time is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(Date value) {
            addCriterion("modify_time =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(Date value) {
            addCriterion("modify_time <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(Date value) {
            addCriterion("modify_time >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("modify_time >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(Date value) {
            addCriterion("modify_time <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("modify_time <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<Date> values) {
            addCriterion("modify_time in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<Date> values) {
            addCriterion("modify_time not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(Date value1, Date value2) {
            addCriterion("modify_time between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("modify_time not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNull() {
            addCriterion("del_flag is null");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNotNull() {
            addCriterion("del_flag is not null");
            return (Criteria) this;
        }

        public Criteria andDelFlagEqualTo(Integer value) {
            addCriterion("del_flag =", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotEqualTo(Integer value) {
            addCriterion("del_flag <>", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThan(Integer value) {
            addCriterion("del_flag >", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("del_flag >=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThan(Integer value) {
            addCriterion("del_flag <", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThanOrEqualTo(Integer value) {
            addCriterion("del_flag <=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagIn(List<Integer> values) {
            addCriterion("del_flag in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotIn(List<Integer> values) {
            addCriterion("del_flag not in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagBetween(Integer value1, Integer value2) {
            addCriterion("del_flag between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("del_flag not between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Long value) {
            addCriterion("version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Long value) {
            addCriterion("version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Long value) {
            addCriterion("version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Long value) {
            addCriterion("version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Long value) {
            addCriterion("version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Long value) {
            addCriterion("version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Long> values) {
            addCriterion("version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Long> values) {
            addCriterion("version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Long value1, Long value2) {
            addCriterion("version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Long value1, Long value2) {
            addCriterion("version not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andExpand1IsNull() {
            addCriterion("expand_1 is null");
            return (Criteria) this;
        }

        public Criteria andExpand1IsNotNull() {
            addCriterion("expand_1 is not null");
            return (Criteria) this;
        }

        public Criteria andExpand1EqualTo(String value) {
            addCriterion("expand_1 =", value, "expand1");
            return (Criteria) this;
        }

        public Criteria andExpand1NotEqualTo(String value) {
            addCriterion("expand_1 <>", value, "expand1");
            return (Criteria) this;
        }

        public Criteria andExpand1GreaterThan(String value) {
            addCriterion("expand_1 >", value, "expand1");
            return (Criteria) this;
        }

        public Criteria andExpand1GreaterThanOrEqualTo(String value) {
            addCriterion("expand_1 >=", value, "expand1");
            return (Criteria) this;
        }

        public Criteria andExpand1LessThan(String value) {
            addCriterion("expand_1 <", value, "expand1");
            return (Criteria) this;
        }

        public Criteria andExpand1LessThanOrEqualTo(String value) {
            addCriterion("expand_1 <=", value, "expand1");
            return (Criteria) this;
        }

        public Criteria andExpand1Like(String value) {
            addCriterion("expand_1 like", value, "expand1");
            return (Criteria) this;
        }

        public Criteria andExpand1NotLike(String value) {
            addCriterion("expand_1 not like", value, "expand1");
            return (Criteria) this;
        }

        public Criteria andExpand1In(List<String> values) {
            addCriterion("expand_1 in", values, "expand1");
            return (Criteria) this;
        }

        public Criteria andExpand1NotIn(List<String> values) {
            addCriterion("expand_1 not in", values, "expand1");
            return (Criteria) this;
        }

        public Criteria andExpand1Between(String value1, String value2) {
            addCriterion("expand_1 between", value1, value2, "expand1");
            return (Criteria) this;
        }

        public Criteria andExpand1NotBetween(String value1, String value2) {
            addCriterion("expand_1 not between", value1, value2, "expand1");
            return (Criteria) this;
        }

        public Criteria andExpand2IsNull() {
            addCriterion("expand_2 is null");
            return (Criteria) this;
        }

        public Criteria andExpand2IsNotNull() {
            addCriterion("expand_2 is not null");
            return (Criteria) this;
        }

        public Criteria andExpand2EqualTo(String value) {
            addCriterion("expand_2 =", value, "expand2");
            return (Criteria) this;
        }

        public Criteria andExpand2NotEqualTo(String value) {
            addCriterion("expand_2 <>", value, "expand2");
            return (Criteria) this;
        }

        public Criteria andExpand2GreaterThan(String value) {
            addCriterion("expand_2 >", value, "expand2");
            return (Criteria) this;
        }

        public Criteria andExpand2GreaterThanOrEqualTo(String value) {
            addCriterion("expand_2 >=", value, "expand2");
            return (Criteria) this;
        }

        public Criteria andExpand2LessThan(String value) {
            addCriterion("expand_2 <", value, "expand2");
            return (Criteria) this;
        }

        public Criteria andExpand2LessThanOrEqualTo(String value) {
            addCriterion("expand_2 <=", value, "expand2");
            return (Criteria) this;
        }

        public Criteria andExpand2Like(String value) {
            addCriterion("expand_2 like", value, "expand2");
            return (Criteria) this;
        }

        public Criteria andExpand2NotLike(String value) {
            addCriterion("expand_2 not like", value, "expand2");
            return (Criteria) this;
        }

        public Criteria andExpand2In(List<String> values) {
            addCriterion("expand_2 in", values, "expand2");
            return (Criteria) this;
        }

        public Criteria andExpand2NotIn(List<String> values) {
            addCriterion("expand_2 not in", values, "expand2");
            return (Criteria) this;
        }

        public Criteria andExpand2Between(String value1, String value2) {
            addCriterion("expand_2 between", value1, value2, "expand2");
            return (Criteria) this;
        }

        public Criteria andExpand2NotBetween(String value1, String value2) {
            addCriterion("expand_2 not between", value1, value2, "expand2");
            return (Criteria) this;
        }

        public Criteria andExpand3IsNull() {
            addCriterion("expand_3 is null");
            return (Criteria) this;
        }

        public Criteria andExpand3IsNotNull() {
            addCriterion("expand_3 is not null");
            return (Criteria) this;
        }

        public Criteria andExpand3EqualTo(String value) {
            addCriterion("expand_3 =", value, "expand3");
            return (Criteria) this;
        }

        public Criteria andExpand3NotEqualTo(String value) {
            addCriterion("expand_3 <>", value, "expand3");
            return (Criteria) this;
        }

        public Criteria andExpand3GreaterThan(String value) {
            addCriterion("expand_3 >", value, "expand3");
            return (Criteria) this;
        }

        public Criteria andExpand3GreaterThanOrEqualTo(String value) {
            addCriterion("expand_3 >=", value, "expand3");
            return (Criteria) this;
        }

        public Criteria andExpand3LessThan(String value) {
            addCriterion("expand_3 <", value, "expand3");
            return (Criteria) this;
        }

        public Criteria andExpand3LessThanOrEqualTo(String value) {
            addCriterion("expand_3 <=", value, "expand3");
            return (Criteria) this;
        }

        public Criteria andExpand3Like(String value) {
            addCriterion("expand_3 like", value, "expand3");
            return (Criteria) this;
        }

        public Criteria andExpand3NotLike(String value) {
            addCriterion("expand_3 not like", value, "expand3");
            return (Criteria) this;
        }

        public Criteria andExpand3In(List<String> values) {
            addCriterion("expand_3 in", values, "expand3");
            return (Criteria) this;
        }

        public Criteria andExpand3NotIn(List<String> values) {
            addCriterion("expand_3 not in", values, "expand3");
            return (Criteria) this;
        }

        public Criteria andExpand3Between(String value1, String value2) {
            addCriterion("expand_3 between", value1, value2, "expand3");
            return (Criteria) this;
        }

        public Criteria andExpand3NotBetween(String value1, String value2) {
            addCriterion("expand_3 not between", value1, value2, "expand3");
            return (Criteria) this;
        }

        public Criteria andExpand4IsNull() {
            addCriterion("expand_4 is null");
            return (Criteria) this;
        }

        public Criteria andExpand4IsNotNull() {
            addCriterion("expand_4 is not null");
            return (Criteria) this;
        }

        public Criteria andExpand4EqualTo(String value) {
            addCriterion("expand_4 =", value, "expand4");
            return (Criteria) this;
        }

        public Criteria andExpand4NotEqualTo(String value) {
            addCriterion("expand_4 <>", value, "expand4");
            return (Criteria) this;
        }

        public Criteria andExpand4GreaterThan(String value) {
            addCriterion("expand_4 >", value, "expand4");
            return (Criteria) this;
        }

        public Criteria andExpand4GreaterThanOrEqualTo(String value) {
            addCriterion("expand_4 >=", value, "expand4");
            return (Criteria) this;
        }

        public Criteria andExpand4LessThan(String value) {
            addCriterion("expand_4 <", value, "expand4");
            return (Criteria) this;
        }

        public Criteria andExpand4LessThanOrEqualTo(String value) {
            addCriterion("expand_4 <=", value, "expand4");
            return (Criteria) this;
        }

        public Criteria andExpand4Like(String value) {
            addCriterion("expand_4 like", value, "expand4");
            return (Criteria) this;
        }

        public Criteria andExpand4NotLike(String value) {
            addCriterion("expand_4 not like", value, "expand4");
            return (Criteria) this;
        }

        public Criteria andExpand4In(List<String> values) {
            addCriterion("expand_4 in", values, "expand4");
            return (Criteria) this;
        }

        public Criteria andExpand4NotIn(List<String> values) {
            addCriterion("expand_4 not in", values, "expand4");
            return (Criteria) this;
        }

        public Criteria andExpand4Between(String value1, String value2) {
            addCriterion("expand_4 between", value1, value2, "expand4");
            return (Criteria) this;
        }

        public Criteria andExpand4NotBetween(String value1, String value2) {
            addCriterion("expand_4 not between", value1, value2, "expand4");
            return (Criteria) this;
        }

        public Criteria andExpand5IsNull() {
            addCriterion("expand_5 is null");
            return (Criteria) this;
        }

        public Criteria andExpand5IsNotNull() {
            addCriterion("expand_5 is not null");
            return (Criteria) this;
        }

        public Criteria andExpand5EqualTo(String value) {
            addCriterion("expand_5 =", value, "expand5");
            return (Criteria) this;
        }

        public Criteria andExpand5NotEqualTo(String value) {
            addCriterion("expand_5 <>", value, "expand5");
            return (Criteria) this;
        }

        public Criteria andExpand5GreaterThan(String value) {
            addCriterion("expand_5 >", value, "expand5");
            return (Criteria) this;
        }

        public Criteria andExpand5GreaterThanOrEqualTo(String value) {
            addCriterion("expand_5 >=", value, "expand5");
            return (Criteria) this;
        }

        public Criteria andExpand5LessThan(String value) {
            addCriterion("expand_5 <", value, "expand5");
            return (Criteria) this;
        }

        public Criteria andExpand5LessThanOrEqualTo(String value) {
            addCriterion("expand_5 <=", value, "expand5");
            return (Criteria) this;
        }

        public Criteria andExpand5Like(String value) {
            addCriterion("expand_5 like", value, "expand5");
            return (Criteria) this;
        }

        public Criteria andExpand5NotLike(String value) {
            addCriterion("expand_5 not like", value, "expand5");
            return (Criteria) this;
        }

        public Criteria andExpand5In(List<String> values) {
            addCriterion("expand_5 in", values, "expand5");
            return (Criteria) this;
        }

        public Criteria andExpand5NotIn(List<String> values) {
            addCriterion("expand_5 not in", values, "expand5");
            return (Criteria) this;
        }

        public Criteria andExpand5Between(String value1, String value2) {
            addCriterion("expand_5 between", value1, value2, "expand5");
            return (Criteria) this;
        }

        public Criteria andExpand5NotBetween(String value1, String value2) {
            addCriterion("expand_5 not between", value1, value2, "expand5");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_wheat_financial_order
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_wheat_financial_order
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}