package com.spring.fee.dao.mapper;

import com.spring.fee.model.TableInvest;
import com.spring.fee.model.TableInvestExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TableInvestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_invest
     *
     * @mbggenerated
     */
    int countByExample(TableInvestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_invest
     *
     * @mbggenerated
     */
    int deleteByExample(TableInvestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_invest
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_invest
     *
     * @mbggenerated
     */
    int insert(TableInvest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_invest
     *
     * @mbggenerated
     */
    int insertSelective(TableInvest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_invest
     *
     * @mbggenerated
     */
    List<TableInvest> selectByExample(TableInvestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_invest
     *
     * @mbggenerated
     */
    TableInvest selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_invest
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TableInvest record, @Param("example") TableInvestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_invest
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TableInvest record, @Param("example") TableInvestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_invest
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TableInvest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_invest
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TableInvest record);
}