package com.spring.fee.dao.mapper;

import com.spring.fee.model.TableMemberLevelChangeDetail;
import com.spring.fee.model.TableMemberLevelChangeDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TableMemberLevelChangeDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_member_level_change_detail
     *
     * @mbggenerated
     */
    int countByExample(TableMemberLevelChangeDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_member_level_change_detail
     *
     * @mbggenerated
     */
    int deleteByExample(TableMemberLevelChangeDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_member_level_change_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_member_level_change_detail
     *
     * @mbggenerated
     */
    int insert(TableMemberLevelChangeDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_member_level_change_detail
     *
     * @mbggenerated
     */
    int insertSelective(TableMemberLevelChangeDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_member_level_change_detail
     *
     * @mbggenerated
     */
    List<TableMemberLevelChangeDetail> selectByExample(TableMemberLevelChangeDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_member_level_change_detail
     *
     * @mbggenerated
     */
    TableMemberLevelChangeDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_member_level_change_detail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TableMemberLevelChangeDetail record, @Param("example") TableMemberLevelChangeDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_member_level_change_detail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TableMemberLevelChangeDetail record, @Param("example") TableMemberLevelChangeDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_member_level_change_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TableMemberLevelChangeDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_member_level_change_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TableMemberLevelChangeDetail record);
}