package com.spring.fee.dao.mapper;

import com.spring.fee.model.TableRankSetting;
import com.spring.fee.model.TableRankSettingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TableRankSettingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_rank_setting
     *
     * @mbggenerated
     */
    int countByExample(TableRankSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_rank_setting
     *
     * @mbggenerated
     */
    int deleteByExample(TableRankSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_rank_setting
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_rank_setting
     *
     * @mbggenerated
     */
    int insert(TableRankSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_rank_setting
     *
     * @mbggenerated
     */
    int insertSelective(TableRankSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_rank_setting
     *
     * @mbggenerated
     */
    List<TableRankSetting> selectByExample(TableRankSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_rank_setting
     *
     * @mbggenerated
     */
    TableRankSetting selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_rank_setting
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TableRankSetting record, @Param("example") TableRankSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_rank_setting
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TableRankSetting record, @Param("example") TableRankSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_rank_setting
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TableRankSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_rank_setting
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TableRankSetting record);
}