package com.spring.fee.dao.mapper;

import com.spring.fee.model.TableMemberGoods;
import com.spring.fee.model.TableMemberGoodsDZ;
import com.spring.fee.model.TableMemberGoodsExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TableMemberGoodsMapperDZ {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_member_goods
     *
     * @mbggenerated
     */
    List<TableMemberGoods> selectByExample(TableMemberGoodsDZ example);

}