package com.spring.fee.dao.mapper;

import com.spring.fee.model.TableMemberAccountDetail;
import com.spring.fee.model.TableMemberAccountDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TableMemberAccountDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_member_account_detail
     *
     * @mbggenerated
     */
    int countByExample(TableMemberAccountDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_member_account_detail
     *
     * @mbggenerated
     */
    int deleteByExample(TableMemberAccountDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_member_account_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_member_account_detail
     *
     * @mbggenerated
     */
    int insert(TableMemberAccountDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_member_account_detail
     *
     * @mbggenerated
     */
    int insertSelective(TableMemberAccountDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_member_account_detail
     *
     * @mbggenerated
     */
    List<TableMemberAccountDetail> selectByExample(TableMemberAccountDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_member_account_detail
     *
     * @mbggenerated
     */
    TableMemberAccountDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_member_account_detail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TableMemberAccountDetail record, @Param("example") TableMemberAccountDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_member_account_detail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TableMemberAccountDetail record, @Param("example") TableMemberAccountDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_member_account_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TableMemberAccountDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_member_account_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TableMemberAccountDetail record);
}