package com.spring.fee.dao.mapper;

import com.spring.fee.model.TableMemberTransfer;
import com.spring.fee.model.TableMemberTransferExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TableMemberTransferMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_member_transfer
     *
     * @mbggenerated
     */
    int countByExample(TableMemberTransferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_member_transfer
     *
     * @mbggenerated
     */
    int deleteByExample(TableMemberTransferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_member_transfer
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_member_transfer
     *
     * @mbggenerated
     */
    int insert(TableMemberTransfer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_member_transfer
     *
     * @mbggenerated
     */
    int insertSelective(TableMemberTransfer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_member_transfer
     *
     * @mbggenerated
     */
    List<TableMemberTransfer> selectByExample(TableMemberTransferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_member_transfer
     *
     * @mbggenerated
     */
    TableMemberTransfer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_member_transfer
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TableMemberTransfer record, @Param("example") TableMemberTransferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_member_transfer
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TableMemberTransfer record, @Param("example") TableMemberTransferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_member_transfer
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TableMemberTransfer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_member_transfer
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TableMemberTransfer record);
}