package com.spring.fee.dao.mapper;

import com.spring.fee.model.TableTask;
import com.spring.fee.model.TableTaskExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TableTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_task
     *
     * @mbggenerated
     */
    int countByExample(TableTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_task
     *
     * @mbggenerated
     */
    int deleteByExample(TableTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_task
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_task
     *
     * @mbggenerated
     */
    int insert(TableTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_task
     *
     * @mbggenerated
     */
    int insertSelective(TableTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_task
     *
     * @mbggenerated
     */
    List<TableTask> selectByExample(TableTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_task
     *
     * @mbggenerated
     */
    TableTask selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_task
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TableTask record, @Param("example") TableTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_task
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TableTask record, @Param("example") TableTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_task
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TableTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_task
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TableTask record);
}