package com.spring.fee.dao.mapper;

import com.spring.fee.model.TInvestPlanDetail;
import com.spring.fee.model.TInvestPlanDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TInvestPlanDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_plan_detail
     *
     * @mbggenerated
     */
    int countByExample(TInvestPlanDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_plan_detail
     *
     * @mbggenerated
     */
    int deleteByExample(TInvestPlanDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_plan_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_plan_detail
     *
     * @mbggenerated
     */
    int insert(TInvestPlanDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_plan_detail
     *
     * @mbggenerated
     */
    int insertSelective(TInvestPlanDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_plan_detail
     *
     * @mbggenerated
     */
    List<TInvestPlanDetail> selectByExample(TInvestPlanDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_plan_detail
     *
     * @mbggenerated
     */
    TInvestPlanDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_plan_detail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TInvestPlanDetail record, @Param("example") TInvestPlanDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_plan_detail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TInvestPlanDetail record, @Param("example") TInvestPlanDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_plan_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TInvestPlanDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_plan_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TInvestPlanDetail record);
}