package com.spring.fee.dao.mapper;

import com.spring.fee.model.TInvestMemberMoneyConfig;
import com.spring.fee.model.TInvestMemberMoneyConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TInvestMemberMoneyConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_member_money_config
     *
     * @mbggenerated
     */
    int countByExample(TInvestMemberMoneyConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_member_money_config
     *
     * @mbggenerated
     */
    int deleteByExample(TInvestMemberMoneyConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_member_money_config
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_member_money_config
     *
     * @mbggenerated
     */
    int insert(TInvestMemberMoneyConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_member_money_config
     *
     * @mbggenerated
     */
    int insertSelective(TInvestMemberMoneyConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_member_money_config
     *
     * @mbggenerated
     */
    List<TInvestMemberMoneyConfig> selectByExample(TInvestMemberMoneyConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_member_money_config
     *
     * @mbggenerated
     */
    TInvestMemberMoneyConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_member_money_config
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TInvestMemberMoneyConfig record, @Param("example") TInvestMemberMoneyConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_member_money_config
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TInvestMemberMoneyConfig record, @Param("example") TInvestMemberMoneyConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_member_money_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TInvestMemberMoneyConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_member_money_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TInvestMemberMoneyConfig record);
}