package com.spring.fee.dao.mapper;

import com.spring.fee.model.TInvestPlanMainLog;
import com.spring.fee.model.TInvestPlanMainLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TInvestPlanMainLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_plan_main_log
     *
     * @mbggenerated
     */
    int countByExample(TInvestPlanMainLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_plan_main_log
     *
     * @mbggenerated
     */
    int deleteByExample(TInvestPlanMainLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_plan_main_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_plan_main_log
     *
     * @mbggenerated
     */
    int insert(TInvestPlanMainLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_plan_main_log
     *
     * @mbggenerated
     */
    int insertSelective(TInvestPlanMainLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_plan_main_log
     *
     * @mbggenerated
     */
    List<TInvestPlanMainLog> selectByExample(TInvestPlanMainLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_plan_main_log
     *
     * @mbggenerated
     */
    TInvestPlanMainLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_plan_main_log
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TInvestPlanMainLog record, @Param("example") TInvestPlanMainLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_plan_main_log
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TInvestPlanMainLog record, @Param("example") TInvestPlanMainLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_plan_main_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TInvestPlanMainLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_plan_main_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TInvestPlanMainLog record);
}